### ISSUE TITLE
UI Picker view not showing correctly ios 11 xcode 9

### ISSUE THREAD

**Issue by AfrozZaheer** [hackiftekhar/IQKeyboardManager#1020]
Hi, There is problem with picker view use as input view of UITextField while IQKeyboard is enable. 
working fine in ios 10, this issue seems to be related to ios 11. Attached is issue picture where there is a huge gap between toolbar and picker.  

![simulator screen shot - iphone 7 - 2017-09-27 at 15 57 49](https://user-images.githubusercontent.com/25176835/30952143-1302278c-a440-11e7-858b-a817166d929d.png)

**Comment by Ashu** [comment]
You need to specify height of the picker i.e. 216. It will fix the issue.

**Comment by ab-rdarts** [comment]
I see the same for non pickerviews (IQKeyboardManager 5.0.2)

![simulator screen shot - iphone x - 2017-09-28 at 18 57 00](https://user-images.githubusercontent.com/9376541/30977109-4002e3f4-a47f-11e7-8172-82ed23c865f1.png)

**Comment by hackiftekhar** [comment]
That doesn't look good. Are you sure you haven't added this modal directly to UIWindow. Are you sure this modal is a part of a UIViewController?

**Comment by ab-rdarts** [comment]
Yes, sure. It happens also on another screen. For example in view controller which was pushed into navigation controller. As I see it appears only at the second appearance of viewcontroller. It seems I've fixed it by forcing view.endEditing at viewcontroller disappearance. 
The strange thing that this toolbar is shown in right position in view hierarchy. And done button can be clicked in the right position also, but toolbar is drawn in the wrong position

**Comment by hackiftekhar** [comment]
This looks too odd, can you try to put this in a demo project for me?

**Comment by IntellectSoftDeveloper** [comment]
I will try on the weekend

**Comment by ab-rdarts** [comment]
I will try on the weekend

**Comment by hackiftekhar** [comment]
Sure!

**Comment by ab-rdarts** [comment]
Sample project is attached. It has two problems with keyboard on iOS11
1. Steps to reproduce (Any iPhone version):
a. Press Menu -> Settings
b. Activate any text field
c. Press Back, than again Settings
d. Activate any text field. Here you will see problem with toolbar. As I see it can be related to Hero library, but it can be reproduced only iOS11.
It seems bug disappears If you uncomment //view.endEditing(true) inside SettingsViewController

2. Steps to reproduce another problems (only iPhoneX, not related to Hero)
a. Press Modal
b. At start space between textfield and keyboard is wrong. According to source code it should be 100 px.
c. Also if you start switch First/Second segment control you will see that this space random, sometimes 100px, sometimes not. 
d. Also screen sometimes placed into wrong position at bottom when keyboard has disappeared. It should be related to safe area but not to the view bottom

[TestKeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1346390/TestKeyboard.zip)

**Comment by hackiftekhar** [comment]
Thanks @ab-rdarts for adding the demo. Here is my feedback
1. For this issue I investigated it and haven't found any clues why toolbar shows like floating in the sky. However for a workaround you should always dismiss keyboard if you are navigating to other controller from current. So I suggest you to do the workaround you you were doing.
2. For step2 I found that you are calling `textField.becomeFirstResponder()` too early. because the main view of `TextViewController` isn't correctly positioned all view positions, so calling `textField.becomeFirstResponder()` too early provide wrong position of textField which causes to adjust keyboard and textField position in bad position. I would suggest you to manage some kind of bool and call `textField.becomeFirstResponder()` method in viewDidAppear method which will provide you the expected results.

**Comment by ab-rdarts** [comment]
1. Ok about first issue
2. But it doesn’t work even if it appears after viewdidload. So at first time it shows correct position, but on switching by segment control it works wrong again. And in that moment all controls have their right positions already

**Comment by AfrozZaheer** [comment]
Hi, IQKeyboardManager works fine on iOS 10 but this issue appears in iOS 11. It will be great if you fix this ASAP.

**Comment by theolof** [comment]
The toolbar position gets shifted upwards the same height as the keyboard for every time you leave the UIViewController and go back without first dismissing the keyboard. So the second time, the toolbar becomes "invisible" since it's above the screen.

Workaround for me is:

```
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        view.endEditing(true)
    }
```
in all UIViewControllers that use the keyboard.

**Comment by ab-rdarts** [comment]
theolof thanx but this workaround is just about first issue and it was mentioned earlier. Also this workaround doesn't solve issue with wrong space in my case

**Comment by AfrozZaheer** [comment]
Hi Finally I find solution 
self.pickerView.translatesAutoresizingMaskIntoConstraints = false

Hope this help.

**Comment by Malav1879** [comment]
AfrozZaheer  thanks is working (y)

**Comment by stachon** [comment]
I suggest that the above tip is added to `KNOWN ISSUES.md`
