### ISSUE TITLE
All is good. One challenge

### ISSUE THREAD

**Issue by davestucky** [hackiftekhar/IQKeyboardManager#1035]
OK after much cursing and sweat IQKeyboard works. Challenge was incomplete update of xcode. Now I have 
----------
 if let itemLayoutGuide : UILayoutSupport = layoutGuide {
                    
                    if (itemLayoutGuide === viewController.topLayoutGuide)    //If topLayoutGuide constraint
                    {
                        layoutGuidePosition = .top
                    }
                    else if (itemLayoutGuide === viewController.bottomLayoutGuide)    //If bottomLayoutGuice constraint
                    {
                        layoutGuidePosition = .bottom
                    }
--------two errors (same challenge) 
'topLayoutGuide' was deprecated in iOS 11.0
'bottomLayoutGuide' was deprecated in iOS 11.0

Thanks again and I really appreciate your quick responses to my requests. Again GREAT framework! Love it.

Dave

**Comment by hackiftekhar** [comment]
Now I've optimized project to support Safe Area. So if you are using Safe Area then there will be no need to do any additional tweaks for top layout guide and bottom layout guide, from now library will try to do tweak by changing additionalSafeAreaInsets property of viewController. Let's see how it works because I'm not aware of all the user scenarios and I wrote a basic workaround.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
