### ISSUE TITLE
Basic video tutorial

### ISSUE THREAD

**Issue by rebeloper** [hackiftekhar/IQKeyboardManager#1135]
Hi,

I have created two videos on how to implement IQKeyboardManager at it's core:

https://www.youtube.com/playlist?list=PL_csAAO9PQ8aTL87XnueOXi3RpWE2m_8v

**Comment by hackiftekhar** [comment]
Hey @rebeloper That's awesome! I can include this in the readme file. 

I checked both videos and just one thing I noticed, while demoing you've added constraint pinned to safe area (top on textView and bottom on textField) and that's why you get some jumping layout issue while demoing and switching between textField and textView. Can you replace that constraint with superview to remove jumping layout issue? Or if it will be hard for you to do then just let me know we can include these video links without any change in repo readme file. Thanks mate!

**Comment by rebeloper** [comment]
Hi,

I have changed the top constraint of the textView to be anchored to the Superview, and the bottom constraint of the textField to be anchored to the Superview, but still no change. The jumping layout issue remains.

<img width="1440" alt="screen shot 2017-11-16 at 13 43 07" src="https://user-images.githubusercontent.com/2488011/32889587-250095da-cad4-11e7-933c-d56f3beda28e.png">
<img width="1440" alt="screen shot 2017-11-16 at 13 43 18" src="https://user-images.githubusercontent.com/2488011/32889588-251c7e94-cad4-11e7-91f2-e6c654165c7f.png">

Any advice? I would like to create a third video with this fix.

**Comment by hackiftekhar** [comment]
Nope, I think this should fix the issue, if not then I'll need to check what might be the problem, I'm was sure that library should work out of the box.

Anyhow then I'll include those video links in README file.

**Comment by hackiftekhar** [comment]
Added to README. Cheers!

**Comment by rebeloper** [comment]
Awesome. Could you please add this image with the YouTube link to the ReadMe too? People tend to click on images more. Thank you.

![keyboardmagic](https://user-images.githubusercontent.com/2488011/32949831-e00af55e-cbac-11e7-8f7d-cdb78fd1ad96.jpg)

**Comment by hackiftekhar** [comment]
Sure! Will do.

**Comment by hackiftekhar** [comment]
done!

**Comment by gnshkamath** [comment]
In the videos, @rebeloper you had added the text field (bottom view) before adding the text view (top view).

The subviews of the main view had the following order:
1: text field (bottom view)
2: text view (top view)

Hence, the up/down arrows in the toolbar got messed up. That's when I realised how consistent is IQKeyboardManager - what you give is what you get.

@hackiftekhar an awesome and beautiful library.
@rebeloper thanks for the videos. They really showed how simple it is to integrate this library.
