### ISSUE TITLE
xocde9.2，IQKeyboardManager6.0.1

### ISSUE THREAD

**Issue by xhzth7091** [hackiftekhar/IQKeyboardManager#1329]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
![0ef435a1-e816-4326-a20e-cb65ae0bb7bf](https://user-images.githubusercontent.com/13980546/39566667-ef5ec560-4eee-11e8-9f83-480db65bc21c.png)

The keyboard didn't change, and the return car didn't respond.
![2](https://user-images.githubusercontent.com/13980546/39566670-f22d8402-4eee-11e8-9489-80553f242a07.png)

No arrow
**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.6

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
I'll try to check what might be the issue

**Comment by hackiftekhar** [comment]
@xhzth7091 I'm not sure why you aren't seeing the return key as next while it should be. I checked with my demo app and it works for me. However I know the cause of prev/next button not showing. It's because you might have textFields on different superviews. Can you please send me more information about the return key handler, a demo project would be good.

**Comment by hackiftekhar** [comment]
@xhzth7091 Can you please share more info and a demo project here?
