### ISSUE TITLE
Can't change button text throughout the app

### ISSUE THREAD

**Issue by Divakar-Murugesh** [hackiftekhar/IQKeyboardManager#1346]
### Description

I want to change my button text based on server response. But after implementation of IQKeyboardManager Library. I can't change my button text. If I assign new text to button > Library replace the button text with old text I can see the text change animation.

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.4

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 8 Plus

**Library Version:** 6.0.3

Please fix this as soon as possible

**Comment by hackiftekhar** [comment]
Can you please share screenshot and demo?

**Comment by Divakar-Murugesh** [comment]
Please check this... 
https://github.com/Divakar-Murugesh/IQKeyboardManager_issues_1346

**Comment by hackiftekhar** [comment]
I checked the video @Divakar-Murugesh. First of all, it's not related to the library at all.

Secondly, to change the button text, you shouldn't change `button.titleLabel.text`, instead of this you have to change title for it's states like this `sender.setTitle("newTitle", for: .normal)`. I hope this will solve your problem.
