### ISSUE TITLE
UITableView don't scroll to bottom

### ISSUE THREAD

**Issue by ArslanAsimSwoo** [hackiftekhar/IQKeyboardManager#1351]
### Description
I have tableview inside a uiviewcontroller and text field which is part of uiview not table view, when keyboard shows tableview content size didn't reduce and it can't scroll to bottom
### Steps to Reproduce
Following is structure of my view

<img width="252" alt="screen shot 2018-05-30 at 10 51 03 am" src="https://user-images.githubusercontent.com/38398394/40703795-6ae4c80c-63f7-11e8-90f7-833b97face10.png">

**Expected behavior:** Table view should scroll to bottom when text field is editing 

**Actual behavior:** Table view don't  scroll to bottom

**Reproduces how often:** always

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 8

**Library Version:** 5.0.8

**Comment by hackiftekhar** [comment]
This case cannot be handled by the library since in this case library only knows about your textField and that's it. Because your textField is independent so library doesn't even know that there is a tableview at the bottom. Unfortunately this situation cannot be handled automatically and you have to write some of your own logic to change tableView contentInset.
