### ISSUE TITLE
about uiseachbar

### ISSUE THREAD

**Issue by 964562398** [hackiftekhar/IQKeyboardManager#1367]
hi i got Problems with UISearchBar，The UITextField also the same problem，I attached a 
sample project to showcase the issue:
[searchbartest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2097726/searchbartest.zip)

**Comment by hackiftekhar** [comment]
I checked the demo app but it looks like your issue can't be fixed by library since it's a complex UI at the bottom part where library tries to adjust collectionView's contentInset but it leads to some UI bugs. I suggest you to disable library in this controller and handle keyboard by registering keyboard events.
