### ISSUE TITLE
Swift 4.2 and Xcode  10 Support ??

### ISSUE THREAD

**Issue by techmehra** [hackiftekhar/IQKeyboardManager#1432]

**Comment by maslovsa** [comment]
me too

**Comment by hackiftekhar** [comment]
What issues you are getting? I think the latest code works with Xcode10 with 4.2 swift. I migrated couple of months ago.

**Comment by 814349837** [comment]
Carthage not support swift4.2

**Comment by 814349837** [comment]
> What issues you are getting? I think the latest code works with Xcode10 with 4.2 swift. I migrated couple of months ago.

how get Carthage support swift 4.2 `Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler:`

**Comment by codeguesser** [comment]
![image](https://user-images.githubusercontent.com/1662117/45730191-eb64ac00-bc02-11e8-82f7-12bd21e93764.png)

**Comment by fetzig** [comment]
have a similar issue when trying to convert a Swift 4 workspace/project to 4.2:

IQKeyboardManagerSwift (6.1.1)
xCode 10, project on swift 4

click convert to swift 4.2 shows 2 targets. main target and IQKeyboardManagerSwift, IQKeyboardManagerSwift isn't listed when i manually set the swift version to 4.2 and call pod update/install. But it doesn't matter. Clean build or remove of DerivedData makes no difference as well. outcome when converting to 4.2 is always:

module map file 'build/Release-iphoneos/IQKeyboardManagerSwift/IQKeyboardManagerSwift.modulemap' not found

**Comment by fetzig** [comment]
UPDATE:

Since removing IQKeyboardManager form the workspace and later adding back is an easy thing to do, I steered clear from the "conversion issue".

If you want to "Convert to Swift 4.2":
 * remove IQKeyboardManager from Podfile and source code (import IQKeyboardManager, a.s.o.)
 * pod install
 * clear build folder and DerivedData (can't hurt)
 * start the convertion/migration assistant in xCode 10 (no errors this time)
 * check if your project builds
 * add pod IQKeyboardManager back to your Podfile and source code
 * pod install
 * build again, no issues should occur

Hope that helped.

**Comment by hackiftekhar** [comment]
At last, the current source code works with Xcode 10 Swift 4.2. Right?

**Comment by fetzig** [comment]
@hackiftekhar in my case, yes

**Comment by hackiftekhar** [comment]
Ok
