### ISSUE TITLE
Black space is displaying after dismiss the keyboard

### ISSUE THREAD

**Issue by Jay-iTechPioneer** [hackiftekhar/IQKeyboardManager#1433]
When i dismiss the keyboard there is black color space in UIView. I have used latest one 6.1.1

**Comment by hackiftekhar** [comment]
Please share demo project

**Comment by sm0nster** [comment]
Same here. I guess it's because of navigation bar - if i hide it programatically the keyboard works perfecly

**Comment by hackiftekhar** [comment]
Can you guys share some more thoughts on this? I don't know at which position you are seeing the black space.

**Comment by darshit261991** [comment]
At the bottom of the screen.

**Comment by hackiftekhar** [comment]
Are you trying to beginFirstResponder your textfield on viewDidLoad?

**Comment by darshit261991** [comment]
Yes

**Comment by hackiftekhar** [comment]
Then this issue might appear, please invoke it on viewDidAppear.

Technically when view is loaded in viewDidLoad, it's not actually resized for the screen size and hasn't added to the UIWindow, UINavigationController hierarchy. That's why it may lead to wrong calculations sometimes.

**Comment by SonnyMore** [comment]
Hello! I use new 6.3.0 pod version and I have this issue too. I didn't use some beginFirstResponder, just open keyboard and swipe back to pop view controller. It works only if u will swipe back but swipe right, not letting go of your finger. so that there is no going back. And u will see black space
