### ISSUE TITLE
whole content got to top...

### ISSUE THREAD

**Issue by TomasHardy** [hackiftekhar/IQKeyboardManager#1435]
whole content got to top when use IQkeyboardmanager without using uiscrollview...

![simulator screen shot - iphone x - 2018-09-20 at 18 32 27](https://user-images.githubusercontent.com/16434201/45820501-86917a80-bd04-11e8-82b8-f88d6fd1e0c4.png)
![simulator screen shot - iphone x - 2018-09-20 at 18 32 44](https://user-images.githubusercontent.com/16434201/45820510-898c6b00-bd04-11e8-8b2e-eff61e0ec8c7.png)

**Comment by hackiftekhar** [comment]
It's beause library doesn't work very well with chat kind of screens due to it's view hierarchy. In chat kind of screen the upper UITableView and UITextField are both on different views (Accordingb to library logic they are not related to each other). So library is doing it's work to maintain textField distance from keyboard, but doesn't know that there is UITableView at the top which is moving to the starus bar.

With chat kind of screens, I usually suggest to disable library for that particular viewController and implement your own solution instead.
