### ISSUE TITLE
Regarding Keyboard Show and hide trigger

### ISSUE THREAD

**Issue by AnkitCodeslay** [hackiftekhar/IQKeyboardManager#1456]
As IQKeyboardManager is using NSNotification for KeyboardWillShow and KeyboardWillHide, I want the a trigger where I can perform some operations when keyboard comes and keyboard goes.

Using NSNotificationCenter Observer in my view, creating problem. My TextViews are in tableview cell. and keyboard is getting changing or application crashes.

**Comment by hackiftekhar** [comment]
There is no such feature implemented in library because developer can achieve the same thing using keyboard notifications as library is using.

You have to observe same keyboard notifications and perform your operations in your own observer and if application crashes then you should find the reason and do appropriate code changes.
