### ISSUE TITLE
Click previous/next arrow button, scroll view could not scroll to the correct location and correctly display the next text field.

### ISSUE THREAD

**Issue by lisafly2014** [hackiftekhar/IQKeyboardManager#1541]
**Describe the bug**
App Demo Address:  https://github.com/lisafly2014/IQKeyboradManagerProblem

I created an login app, which include 3 textFields. I used scroll view, content view and stack view to include all the textFields. The content view class is set to IQPreviousNextView, so the up/down arrow button could show.

**To Reproduce**

1. run the app in  simulator iPhone 6S
2. input something in the 1st tex field, then click arrow button, you will find the next text field could not display suitably. Click the arrow button one by one, you will find the problem. the 1st and 2nd text field could not display properly.

**Expected behavior**
When  click the arrow button, suitable text field could display properly.

**Screenshots**

Demo here: 
https://github.com/lisafly2014/IQKeyboradManagerProblem/blob/master/RPReplay_Final1554437225.MP4

**Demo Project**
 https://github.com/lisafly2014/IQKeyboradManagerProblem

### Versions
**Xcode: **it does not matter
**Mac OS:** MacBook Air or mini Mac
**Simulator/Device:** iPhone 6S
**Simulator/Device Name:** iPhone 6S
**Library Version:**  6.0.4

**Additional context**
No

**Comment by hackiftekhar** [comment]
@lisafly2014 I checked this today and this is really a bug which looks to be hard to fix, however I've 50% figure out why this happens. This usually happens when there are different heights of keyboard per textField and textField anyhow embedded inside an UIScrollView. If you notice than IP Address textfield show a suggestion bar over keyboard while username and password doesn't. This is causing some wrong calculations with contentInset and contentOffset properties.

The issue still occurs after disabling the suggestion bar, but it reduces the occurrence of issue somehow. I'll be keeping this issue open until I figure out how to properly fix this.

**Comment by lisafly2014** [comment]
Thanks very much for your reply. Hope you  fix it early.

**Comment by hackiftekhar** [comment]
I also figure out remaining 50%. It's because when textField is embedded in UIScrollView then in my case the textfield tries to adjust it's position by itself and that's causing issue.
![Screen Shot 2019-04-30 at 1 43 24 PM](https://user-images.githubusercontent.com/3831495/56959922-c6f38980-6b6c-11e9-8c78-496591892b95.png)

**Comment by hackiftekhar** [comment]
By comparing at @pgawlowski demo (#1365) and @lisafly2014 demo I found a common thing. Both demo have a UIScrollView->UIStackView->UITextView hierarchy.

On further investigation, I noticed that this issue mostly happens when above kind of hierarchy found, I also found that using `setContentOffset:animated:` method fix the problem (but created problems for other logics).

So as a workaround, if above kind of hierarchy found then Library will use `setContentOffset:animated:` method, otherwise library will use non-animated method like `contentOffset = offset`. Note that the keyboardDistanceFromTextField will not be preserved with this kind of hierarchy but the jumping effect will be reduced.
