### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by prgnshptlklp** [hackiftekhar/IQKeyboardManager#157]
Please add Universal Framework under IQKeyboardManager Framework Directory, So developers can use it on simulator also.

**Comment by hackiftekhar** [comment]
I'm planning to remove support for KeyboardManager.framework, because it is rarely updated in 2-3 months by me. So it contains old code while the repository have the latest source. I'll leave Framework Target option in demo project. If developer need to build it to framework, then they can do by their own.

   Please suggest if I'm going in a wrong direction. Let me know if you've any better suggestions for me.

**Comment by hackiftekhar** [comment]
Removed support for IQKeyboardManager.framework because it's rarely updated by me. In case someone need to build framework, then framework target option is still there in demo project.
