### ISSUE TITLE
when use a framework named RETableViewManager，IQkeyboardManager  doesn't work.

### ISSUE THREAD

**Issue by wy19901227** [hackiftekhar/IQKeyboardManager#166]
Wish you to fix it.

I have found the reason ,for RETableViewManager have used many UITextField which frame is CGRectNull,But IQKeyboadManager not lose them . So,wish you to fix it,I can't do it. And my project have used Both of them. please.

**Comment by hackiftekhar** [comment]
Not necessary to fix it in a hurry, but will look into this later. Thanks for the bug report.

**Comment by wy19901227** [comment]
I have found the reason ,for RETableViewManager have used many UITextField which frame is CGRectNull,But IQKeyboadManager not lose them . So,wish you to fix it,I can't do it. And my project have used Both of them. please.

**Comment by hackiftekhar** [comment]
For a workaround you can disable IQKeyboardManager in viewDidAppear and enable it again in viewWillDisappear. I'll create a demo project and will try to fix it for RETableViewManager.

**Comment by hackiftekhar** [comment]
I checked RETableViewManager with IQKeyboardManager and found that I'm unable to make it compatible it with RETableViewManager. I need to remove very important code from my library in order to make it compatible with RETableViewManager. If still any support needed then RETableViewManager needs to check for 'isAskingCanBecomeFirstResponder' which is defined in 'IQUIView+Hierchy' in 'textFieldShouldBeginEditing' delegate method.

**Comment by hackiftekhar** [comment]
@wy19901227, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
