### ISSUE TITLE
Dock/Undock Keyboard is not handled

### ISSUE THREAD

**Issue by shiwanithakur** [hackiftekhar/IQKeyboardManager#1681]
I am using iPad iOS 12. Dock Keyboard opens in the mid of the screen leaves some space at the bottom. When i tap on textfield , scrollview is not scrolling , UI is hidden under the keyboard.

Change keyboard setting to Dock , Undock , Split.

**Comment by hackiftekhar** [comment]
Yes, it is intentionally not handled. This is because if we support it then it does not look at the bottom since there will be a black area below the undock and split keyboard
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-01-20 at 19 55 27](https://user-images.githubusercontent.com/3831495/72734200-40318180-3bbf-11ea-861d-6e021dac4daa.png)

**Comment by jacksonhubbard** [comment]
Is there a workaround for this? Such as IQKeyboardManager detecting it is undocked, moving the screen, and then filling the black box with a default color?  I love the simplicity of IQKeyboardManager but am wondering if it would be better to use code to move the keyboard manually so it addresses the undocked keyboard in addition to the standard keyboard.
