### ISSUE TITLE
keyboardWillShowNotifcation is fired twice in UITextView

### ISSUE THREAD

**Issue by DiwakarThapa** [hackiftekhar/IQKeyboardManager#1697]
Hello, I was working on project and I was **UITextView**. I defined **keyboardWillShowNotification** in **viewdidLoad** and it is registered only one throughout my application. This **notification is fired twice**. But in **UITextfield** same notification is fired once. I could figure out what went wrong? or is it the bug of the library?

**Comment by fattalgazi** [comment]
I faced the same situation, even I set ```IQKeyboardManager.shared.enable = false``` , the library keeps working, because there is no ```if privateIsEnabled() == false```  control in  IQKeyboardManager's ```textFieldViewDidBeginEditing``` delegates. So even ```IQKeyboardManager.shared.enable``` is false, this line will be triggerred: 

https://github.com/hackiftekhar/IQKeyboardManager/blob/b0f0a127cca6bb39378447baa2afff74123abd09/IQKeyboardManagerSwift/IQKeyboardManager.swift#L1793

And I believe, that line, forces iOS to simulate ```keyboardWillShowNotification``` twice. 

Solution 1:  set ```IQKeyboardManager.shared.enableAutoToolbar  = false```
Solution 2: call ```IQKeyboardManager.shared.unregisterAllNotifications()``` after you done with the library 
Solution 3 , if you are using ```keyboardWillShowNotification``` in your VC too, then check the keyboard is already showed before doing any calculation. By doing that, the second keyboardWillShowNotification fire will not do anything.

(I'm using IQKeyboardManager in some VC , in their deinit() function I was calling ```IQKeyboardManager.shared.enable = false``` after that, whenever a new VC (which is using ```keyboardWillShowNotification``` to change view's frames ) is created, it's ```keyboardWillShowNotification``` delegate will be fired twice because of the IQKeyboardManager's textFieldViewDidBeginEditing delegate.

**Comment by hackiftekhar** [comment]
Yes, the same line is responsible for the cause. It is written because 
 UITextViewTextDidBeginEditingNotification fires after UIKeyboardWillShowNotification which was causing to not calculate the keyboard height properly that's why we reload the textView.

However now a lot of things has changed in the library so I'll try to remove the line if I found it is not necessary.

**Comment by hackiftekhar** [comment]
I found that we cannot remove that code. If we remove then we will not get the toolbar for the very first time of keyboard appearance for that particular textView.
