### ISSUE TITLE
IQKeyBoardManager not  work in new TableViewController

### ISSUE THREAD

**Issue by MourinhoLove** [hackiftekhar/IQKeyboardManager#1700]
**Describe the bug**

I creat a new TableViewController. when I set  `tableView.contentInsetAdjustmentBehavior = .never `
Than IQKeyBoardManager not  work.

**To Reproduce**
1. In viewWillAppear() I set
`  navigationController?.setNavigationBarHidden(false, animated: animated)
    navigationController?.navigationBar.isHidden = false
    self.navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)`
2. I set tableView.contentInsetAdjustmentBehavior = .never 
3. tableViewCell is staticCell
4. when I remove tableView.contentInsetAdjustmentBehavior = .never .It work. But I want set contentInsetAdjustmentBehavior.
5.other contrller is good. just this viewController has problem.

**Expected behavior**
It wok

**Screenshots**
![IMG_3619](https://user-images.githubusercontent.com/7369710/75841843-af7ad200-5e09-11ea-92cc-39cacf80ba2d.PNG)

<img width="341" alt="截屏2020-03-04上午11 25 29" src="https://user-images.githubusercontent.com/7369710/75842318-edc4c100-5e0a-11ea-96b0-7f64429ce189.png">

### Versions
**Xcode:*Version 11.3.1 (11C504)
**Mac OS: 10.15.3 
**Simulator/Device: IOS13
**Simulator/Device Name:  iPhone XR

**Additional context**

**Comment by hackiftekhar** [comment]
It is intentionally to not do anything on UITableViewController.
Please read section "Moving Content That Is Located Under the Keyboard" here:
https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

It says:
Note that UITableViewController automatically resizes and repositions its table view when there is inline editing of text fields

That's why we ignored to adjust anything when there is a UITableViewController.

**Comment by YogeshPateliOS** [comment]
Hello @hackiftekhar , I am facing same issue can you suggest me how can solve this issue.?
