### ISSUE TITLE
Crash on Xcode 11.3 iOS 13

### ISSUE THREAD

**Issue by yly6518** [hackiftekhar/IQKeyboardManager#1708]
crash log:
context=Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug.
And i fix this bug at file IQUIView+IQKeyboardToolbar.m
Line 293 function
 -(NSString *)drawingToolbarPlaceholder {
...
    else if ([self respondsToSelector:@selector(placeholder)])
    {
        Class selfClass = [self class];
        Ivar ivar = class_getInstanceVariable(selfClass, "_placeholderLabel");
        UILabel *placeholderLabel = object_getIvar(self, ivar);
        return placeholderLabel.text;
//        return [(UITextField*)self placeholder];
    }
}

**Comment by hackiftekhar** [comment]
Original source does not have below lines

Class selfClass = [self class];
Ivar ivar = class_getInstanceVariable(selfClass, "_placeholderLabel");
UILabel placeholderLabel = object_getIvar(self, ivar);
return placeholderLabel.text;

You have modified the original source code and trying to access _placeholderLabel that's why you are getting the crash.

**Comment by yly6518** [comment]
Yes,I fix the bug with next code:
Class selfClass = [self class];
Ivar ivar = class_getInstanceVariable(selfClass, "_placeholderLabel");
UILabel placeholderLabel = object_getIvar(self, ivar);
return placeholderLabel.text;
*****************************
Original source at file IQUIView+IQKeyboardToolbar.m Line 293 cause this bug.
