### ISSUE TITLE
setenableautotoolbar = no causes very first click of textfield to not scroll view up

### ISSUE THREAD

**Issue by shahzadyounas** [hackiftekhar/IQKeyboardManager#171]
I have a UIScrollview with a UITableView+ UITextfield within it.

When in my viewdidload/viewwillappear/viewdidappear i set

[[IQKeyboard manager sharedInstance] setEnableAutoToolBar] = NO (ie i dont want the toolbar to appear at all) then on the very first click of the textfield when screen is loaded, the view doesnt scroll up properly (it appears in background).  When I tap out of the keyboard and then tap into the textfield again, the keyboard shows correctly and scrolls the background correctly.

I have isolated the issue as being when I set the setEnableAutoToolbar  = NO.  As when I remove this line then the entire keyboard/scrolling works correctly on first load/tap and thereafter.

Note that when i change the owner scrollview back to a UIView then this issue doesnt happen.

I only need the owner to be a UIScrollview as I need the navigation bar to show up when the keyboard is showing.

FYI i am testing using latest ios in xcode simulator.

Please help!

**Comment by hackiftekhar** [comment]
Could you please share demo project?

**Comment by shahzadyounas** [comment]
https://drive.google.com/file/d/0BzWgweYzMVzYVElPUUZBbmNITFU/view?usp=sharing

Please take a look...I have checked and with a normal UITextField it works fine...however when using
 https://github.com/fphilipe/PHFComposeBarView this is where the issue happens.  Note that phf uses 
https://github.com/fphilipe/PHFDelegateChain but I can't seem to nail down where the issue is (with your or his code).

When you run the demo for first time you will see that the view doesnt scroll up.  But if you tap out then tap back in it does.  If you change the owner scrollview to a view it works fine.

**Comment by hackiftekhar** [comment]
Issue:- I found that you have set your main view to UIScrollView to not hide NavigationBar but cause of the problem is the same scrollView.

I think it's best to handle this viewController keyboard manually, because IQKeyboardManager doesn't really work great on Chatting Screens. You can try these things:-

1) I really don't suggest you to use IQKeyboardManager for chatting like screen. Disable IQKeyboardManager for this screen and manually handling keyboardNotifications (Because there are many further works you need to do on clicking textField.

2) You can also try to implement all the things in a UITableViewController not on UIViewController. This would be good solution.

3) You can also try to add PHFComposeBarView in the tableView FooterView.

Please let me know if you still got some issues and trying to implement IQKeyboardManager in this screen too.

**Comment by shahzadyounas** [comment]
Thanks for all your help.

I eventually figured it out!

Turns out you must set the content size of the scroll view to be the screen size programatically. You cant just change the main view class to  be a scrollview.

**Comment by shahzadyounas** [comment]
Thank you for all your help with this

the only way to fix this is to set the contentsize of the scrollview programatically (cant just change the main view to a scrollview) and then also set scrolling on that to be NO.
then it works!

**Comment by hackiftekhar** [comment]
Finally it works. I'm very happy to hear this good news from you. :)
