### ISSUE TITLE
Textview move down and then up when go to landscape orientation

### ISSUE THREAD

**Issue by eslami-mhmd** [hackiftekhar/IQKeyboardManager#1736]
Describe problem:
I have a ViewController that embedded into UINavigationController. In ViewController I have a textview that its bottom anchor constrained to bottom safe area and it is first responder.
When I rotate device(landscape), textview moved down and then goes up.

Expected behavior:
When device rotate, textview shuold not move down.

Library version: 6.5.5

**Comment by hackiftekhar** [comment]
This issue cannot be handled since on changing the orientation, technically library is first moving all the components to their original position before the orientation, after the orientation, it recalculates all-new frame and set it.

For now, there is no solution, but I'm open to pull-requests if you can fix this and achieve the expected result.
