### ISSUE TITLE
in one of my controllers toolbar coming only with "Done"button  without "<" and ">" buttons .

### ISSUE THREAD

**Issue by NiteshKumar-webonise** [hackiftekhar/IQKeyboardManager#179]
This library working fine but in one controller where 1st text field is decimal keyboard type.Toolbar which is attached with next, previous and done button not appearing with next and previous button in that controller

**Comment by hackiftekhar** [comment]
Please make sure you added all textField on same UIView. If textFields
are on different UIView the IQKeyboardManager handles them separately.

On Tuesday, March 17, 2015, NiteshKumar-webonise <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/179>.
>


-- 
Sent from My iPhone

**Comment by NiteshKumar-webonise** [comment]
Yes you are right, i just noticed this. Thanks for the answer .

**Comment by snezdoliy** [comment]
@hackiftekhar sorry for asking in closed issue, I just do not want to bring this discussion in a new issue, as this is just possibly enhancement / clarification. 
Is there any possibility to have textfields in separate view within same controller, but add those which are needed to be "tracked" together to a separate `IBOutletCollection` which will be tracked by `IQKeyboardManager` ? I am currently having each UITextField in a wrapper like: 

```
|_Controller View
|__ UIView( for 1px custom border)
|___UIView(for textfield background)
|____UITextField self
...
|__ UIView( for 1px custom border)
|___UIView(for textfield background)
|____UITextField self
```
![screenshot 2015-06-24 13 38 57](https://cloud.githubusercontent.com/assets/1237125/8329048/7d2ced64-1a76-11e5-8e1c-74a84c44e2b1.png)

![screenshot 2015-06-24 13 38 49](https://cloud.githubusercontent.com/assets/1237125/8329051/82434668-1a76-11e5-8e98-9ca77f06a958.png)


I am not sure if subclassing such a view-in-view-in-view will work for me, as it has 2 layers. 
That's why I was thinking of adding only these 3 fields to an IBOutletCollection and then keep an eye of it.
Otherwise I do not have **<** and **>** buttons.

**Comment by hackiftekhar** [comment]
Surely you can do, take a look at -(void)considerToolbarPreviousNextInViewClass:(Class)toolbarPreviousNextConsideredClass; method example at repository demo project.

**Comment by snezdoliy** [comment]
@hackiftekhar thank you for quick response! With example I got how it should work. 
Actually I've managed to do this with just creating UIView subclass and `considering` it with this method. 
After that I made main view on UIViewController to be of this class (from storyboard) and did not need to create separate view in storyboard and add all my subviews with constraints to it. It works, thanks!
