### ISSUE TITLE
Calling becomeFirstResponder  at the beginning of the page will jump twice

### ISSUE THREAD

**Issue by CodeOcenS** [hackiftekhar/IQKeyboardManager#1885]
**Describe the bug**
When I call becomeFirstResponder in the viewDidLoad method on page 2, AND I use the navigation bar to navigate to the next page 2, the page will bounce twice.

**To Reproduce**
1. Create ViewController2
2. Create UITextField 
3. Call becomeFirstResponder in the viewDidLoad method,
4. Push to the ViewController2 through the navigationController
5. You will see the page jump twice
**Expected behavior**
There is no beating
**Screenshots**
NO

**Demo Project**
https://github.com/CodeOcenS/IQKeyboardTest4

### Versions
**Xcode:** 13.3 (13E113)
**Mac OS:** 12.2.1 (21D62)
**Simulator/Device:** 15.4
**Simulator/Device Name:** iPhone SE 3 / iPhone XR(not Simulator)
**Library Version:** 6.5.9

**Additional context**
example codes
```objective-c

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColor.whiteColor;
    self.textField = [[UITextField alloc] initWithFrame:CGRectMake(10, self.view.bounds.size.height-100, self.view.bounds.size.width-20, 50)];
    [self.view addSubview:self.textField];
    self.textField.backgroundColor = UIColor.grayColor;
    
    [self.textField becomeFirstResponder];
}
```

**Comment by hackiftekhar** [comment]
becomeFirstResponder in viewDidLoad is discouraged. The reason behind this is the UI changes are in the middle when loading the new controller and haven't properly got updated since the new screen haven't been shown. That's why the miscalculation happen in library.

Please write becomeFirstResponder in viewDidAppear where we 100% sure that screen have loaded properly.

**Comment by CodeOcenS** [comment]
OK thanks！
