### ISSUE TITLE
It'd be good to give access to keyboard tool bar through singleton instance

### ISSUE THREAD

**Issue by Duraiamuthan** [hackiftekhar/IQKeyboardManager#1980]
**Expected behaviour**
### When there's no title bar button in the tool bar which is present with the keyboard , we expect screen reader to skip it instead it reads out as dimmed button

If We could get access to the toolbar of current appearing keyboard from the project , we can probably remove the titlebar by updating toolbar's **accessbilityItems** from project source code.

**To Reproduce**
1. Turn on the accessibility
2. Click on a textfield and keyboard will appear
3. Now swipe right the focus falls on the centre of tool bar , the empty title button of toolbar and it says dimmed button

**Root cause:**
I tracked down the bug to the file IQUIView+IQKeyboardToolbar.m
and line number 368

**Proposal**
Here is my code change suggestion just for fixing the accessibility issue

 ```
if(titleText){
        //Flexible space
        [items addObject:[[self class] flexibleBarButtonItem]];
        
        //Title button
        toolbar.titleBarButton.title = titleText;
        if (@available(iOS 11.0, *)) {}
        else
        {
            toolbar.titleBarButton.customView.frame = CGRectZero;
        }

        [items addObject:toolbar.titleBarButton];
        
        //Flexible space
        [items addObject:[[self class] flexibleBarButtonItem]];
    }else{
        [items addObject:[[self class] flexibleBarButtonItem]];
        [items addObject:[[self class] flexibleBarButtonItem]];
        [items addObject:[[self class] flexibleBarButtonItem]];

    }
```

**Comment by hackiftekhar** [comment]
It's already public but via each individual textFields by writing like:-

`textField.keyboardToolbar`

I haven't tried the consequences of directly manipulating it, but it's upto you how you wanna use it. I'm not sure if changing this will work as expected.

**Comment by Duraiamuthan** [comment]
Point that I'm trying to make is it'd be more useful to give access to keyboard toolbar through [IQKeyboardManager sharedManager] because when we want to access this globally , we won't have the instance of textfield.

**Comment by hackiftekhar** [comment]
There is no global instance available of toolbaar, this is newly created for every textfield. So you just can't change something globally using a global instance and it takes effect. For toolbar it will not work that way.

**Comment by cbohica** [comment]
I have this same problem, and I think the point has been missed here.  The issue is that the tool bar has a blank area (title) that is accessed via Accessibility mode and the voiceover reads "Dimmed".  This is incorrect as unenabled or unselected controls should not be accessible.  This process is to benefit the sight-impaired user, who should not have to navigate over/through an unused/unwanted control.  In this case, the title control qualifies because it has no text.  The question then becomes something like "how do we tell the toolbar we don't want a text area in it"; the proposed solution replaces the title area with the flexible button when there is no text to be displayed.  A better solution would be to allow the text area to be included/excluded from the toobar (via some configuration or attributes setting) in the first place.  Please note that correcting this functionality would go a long way in "raising your bar" with regards to Accessibility, which is rapidly becoming an important issue in society today, especially in relation to application programming which has been greatly lacking in the past.  Thank you for your consideration.
