### ISSUE TITLE
When use a UITextField on a UITableview of type Group, the SectionHeader flashes

### ISSUE THREAD

**Issue by FW1024** [hackiftekhar/IQKeyboardManager#1996]
**Describe the bug**
[20231109180852.webm](https://github.com/hackiftekhar/IQKeyboardManager/assets/18042082/f0f9da6a-a33e-43b9-bc49-f9bbb7eb750e)

**Demo Project**
Demo here: https://github.com/FW1024/KeyBoardManagerProblem

### Versions
**Xcode:** 15
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by FW1024** [comment]
This problem is resolved when a UIStackView exists between the UITextField and the UITableView.
How can I solve this problem without adding UIStackView.
`                            UIView.animate(withDuration: animationDuration, delay: 0, options: animationCurve, animations: { () -> Void in

                                let animatedContentOffset = textFieldView.superviewOfClassType(UIStackView.self, belowView: scrollView) != nil  //  (Bug ID: #1365, #1508, #1541)

                                if animatedContentOffset {
                                    scrollView.setContentOffset(newContentOffset, animated: UIView.areAnimationsEnabled)
                                } else {
                                    scrollView.contentOffset = newContentOffset
                                }
                            }, completion: { _ in

                                if scrollView is UITableView || scrollView is UICollectionView {
                                    //This will update the next/previous states
                                    self.addToolbarIfRequired()
                                }
                            })`
This code may be causing the malfunction

**Comment by hackiftekhar** [comment]
I have added two more conditions there one is for UICollectionView and another one is for UITableView, so if it's there then setContentOffset function will be used. This fixed the animation when keyboard appears.

However due to an iOS limitation when dismissing the keyboard, the glitch is still there. The glitch is: when we set scrollView.contentInset then scrollView reset it's contentOffset internally (probably using .contentOffset = method), so the animation glitch occurs.
