### ISSUE TITLE
Bug: When use UISheetPresentationController, I touch the text field to activate the keyboard, which causes UI problems

### ISSUE THREAD

**Issue by hyun99999** [hackiftekhar/IQKeyboardManager#2001]
I was checked don't use `becomFirstResponder()`and just touch text field.
The same situation was happend.
Like this.

<img src="https://github.com/hackiftekhar/IQKeyboardManager/assets/69136340/e2ac7996-ded3-48dd-9453-0cac2247beb3" width ="200">

It seems that the problem occurs when I use `UISheetPresentationController`.

_Originally posted by @hyun99999 in https://github.com/hackiftekhar/IQKeyboardManager/issues/1994#issuecomment-1826451378_

**Comment by hackiftekhar** [comment]
As mentioned in the card, please provide me a demo project for it because I'm unable to reproduce the same issue as yours.

**Comment by hyun99999** [comment]
ok i can provide demo project to you, then i will reopen issue.

**Comment by hackiftekhar** [comment]
Thank you!

**Comment by pvalderraman** [comment]
Aquí está tu texto corregido en inglés:  

---

I was having the same issue with some of my views. At first, I thought it had something to do with the `sheetPresentationController`, but then I discovered that the problem was actually caused by the property `IQKeyboardManager.shared.disabledDistanceHandlingClasses`, which automatically pushes everything to the top when presented.  

To avoid this, I had to wrap my `UIHostingController` in a custom-made controller:  

final class FilterByLocationModalViewViewController: UIHostingController<FilterByLocationModalView> { 
    // etc. 
}

Then, you can do something like this:  

let types: [UIViewController.Type] = [
    NewsDetailViewController.self,
    EventDetailViewController.self,
    PictureDetailViewController.self,
    ModalTicketsDeliverViewController.self,
    FilterByLocationModalViewViewController.self
]

IQKeyboardManager.shared.disabledDistanceHandlingClasses = types

Adding `FilterByLocationModalViewViewController` to that list prevents IQKeyboardManager from automatically resizing the UI.
