### ISSUE TITLE
In SwiftUI, the toolbar only appears after the keyboard pops up

### ISSUE THREAD

**Issue by myhusbend** [hackiftekhar/IQKeyboardManager#2002]
In iOS17.0.1, The first time the keyboard appears on the page，the toolbar only appears after the keyboard pops up，Instead of appearing with the keyboard。It is normal on iOS15。

**Environment**
Branch: master '7.0.0'
IDE: Xocde 15
Device: iPhone 15 Pro Simulator
System: iOS 17.0.1
Language: SwiftUI

**Comment by hackiftekhar** [comment]
This is a known issue but I haven't found any workaround for this.

**Comment by hackiftekhar** [comment]
This is fixed!

**Comment by ajunjunandtmac** [comment]
> This is fixed!

@hackiftekhar would you pls kindly tell me the commit id or some codes of this fix, i meet some problem in my work and i want to learn the solution from you.
 i try to find out the code but i cannot find it then, thanks very much

**Comment by hackiftekhar** [comment]
@ajunjunandtmac I might not be able to provide you a single commit id. This is because segregating the library into smaller parts did the trick because each components now have their own responsibilities and they only takes care of their part.

https://github.com/hackiftekhar/IQKeyboardManager/commit/b22e0ab6425fda4d1222856a7b6078a7fd68cbbe
https://github.com/hackiftekhar/IQKeyboardManager/commit/bcf9f0d7bb1cb52ac8ea550b1552ed9ee17df99a
