### ISSUE TITLE
additional bottom gap between the last input box and the keyboard

### ISSUE THREAD

**Issue by ajunjunandtmac** [hackiftekhar/IQKeyboardManager#2027]
SDK Version: v6.5.11
Platform: SwiftUI 2.0

I noticed that you added the following two lines of code to the file IQKeyboardManager+Position.swift in the commit SHA 048178a.
kbFrame.origin.y -= rootControllerConfiguration.beginSafeAreaInsets.bottom
kbFrame.size.height += rootControllerConfiguration.beginSafeAreaInsets.bottom
This will cause an additional bottom gap between the last input box and the keyboard.

Could you please reconsider whether these two lines of code are necessary?
Thank you so much

Attachment is a swiftUI demo
[SwiftUI+IQ.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/14643808/SwiftUI%2BIQ.zip)

screen recording with origin SDK
https://github.com/hackiftekhar/IQKeyboardManager/assets/14208608/f74ddfa7-c7cf-49cd-8321-7c5754fa0ee2

screen recording with the related code deleted
https://github.com/hackiftekhar/IQKeyboardManager/assets/14208608/e9fdc408-edd2-43f9-a973-111b6a6534a5

**Comment by hackiftekhar** [comment]
@ajunjunandtmac Those lines are necessary if someone has put a bottom constraint with safe area layout guide.

When keyboard appears and we change rootView frame, the safe area margin becomes zero. Due to this, the last field get's hidden a little bit behind the keyboard, that's why we are adding safe area's bottom so that in those cases too the keyboard will not hide the textField.

This issue will probably not happen with scrollView
