### ISSUE TITLE
Upload Privacy Policy

### ISSUE THREAD

**Issue by BenoitDeguine** [hackiftekhar/IQKeyboardManager#2035]
Apple says "Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect."

Please add privacy policy so we can update our library
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by phoney** [comment]
The project does have a Privacy Manifest. It was updated a few days ago after the last project release 7.0.2. Hopefully there will be a new release with the updated Privacy Manifest in a week or less so we can have the updated Privacy Manifest a few weeks before the deadline.

You could probably use the commit to download IQKeyboardManager to get the latest Privacy Manifest depending on how you're doing your dependencies. I know CocoaPods can do that.

There is a confusing entry in my PrivacyReport for IQKeyboardManger currently that will probably be fixed with a new release.
