### ISSUE TITLE
IQKeyboardManagerSwift behaves differently in 6.15.16 and 7.1.1

### ISSUE THREAD

**Issue by zeroskylian** [hackiftekhar/IQKeyboardManager#2075]
IQKeyboardManagerSwift behaves differently in 6.15.16 and 7.1.1 

[Demo](https://github.com/zeroskylian/IQKeyboardBehaviorDemo)

- 6.5.16
  <img alt='6_15_16' src="https://raw.githubusercontent.com/zeroskylian/IQKeyboardBehaviorDemo/main/asset/6_15_16.gif" width=30%>

- 7.1.1
  <img alt='7_1_1' src="https://raw.githubusercontent.com/zeroskylian/IQKeyboardBehaviorDemo/main/asset/7_1_1.gif" width=30%>

**Comment by hackiftekhar** [comment]
Hi @zeroskylian, I debugged in both version. However due to newer approach in 7.1.1, there may be an issue with the NextGrowingTextView, you are using.

This is with standard UITextView
https://github.com/user-attachments/assets/b881b909-333d-4fc5-a27c-02009360155b


The NextGrowingTextView has some of it's internal mechanism for changing contentOffset of the UITextView, also there are some different components involve internally in NextGrowingTextView which changes something based on the contentInset and contentOffset of the UITextView on keyboard appearing and typing. Also the internal UITextView does not have full height, it's having around 35 at initial and then it grows as we type.
https://github.com/user-attachments/assets/e5ec7619-f0da-4ff8-b0cc-310aa58c1ded
https://github.com/user-attachments/assets/84778e67-9150-4657-a65a-64733ae24768

So for me, as far as standard UITextView does work in the way it should, I'm not much concerned. Also you may have to look inside the NextGrowingTextView about why it's not positioning the UITextView correctly.
