### ISSUE TITLE
Remove keyboard observability notification when disable IQKeyboardManager

### ISSUE THREAD

**Issue by ehab-al-cko** [hackiftekhar/IQKeyboardManager#2079]
**Describe the bug**
Since `IQKeyboardManager` is a singleton (IQKeyboardManager.shared), 
it takes control of every text field, including those in our project, which is leading to some unexpected behavior.

It seems that `IQKeyboardManager` is registering itself as an observer to the keyboard events but doesn’t remove that observation, which looks like a bug (especially in the Swift version of IQKeyboardManager).

 Remove keyboard observation when 
```swift
 IQKeyboardManager.shared.enable = false
```

**Comment by hackiftekhar** [comment]
We intentionally does not remove observation because if you change this variable to true on the fly (when a textField is active with the keyboard), then the library have to move up the screen to make textField visible. This is why the latest textField and keyboard information is needed even when the library is disabled.

**Comment by ehab-al-cko** [comment]
Can you at least provide public function to unregister and register notification and it can be called manually?

**Comment by ehab-al-cko** [comment]
@hackiftekhar
