### ISSUE TITLE
UITableview header view issue

### ISSUE THREAD

**Issue by furueili** [hackiftekhar/IQKeyboardManager#232]
Hi hackiftekhar,

Thanks for your nice library, it saves a lot of work!

I'm working in a uitableview controller. When suer selects field in uitableview , keyboard will show , and tabview will scroll up.

The problem is section header view not moved up with tableview, please give me some help, thx
![img_7124](https://cloud.githubusercontent.com/assets/1407724/8049868/9b69ff8c-0e97-11e5-9d91-6d019fb66cdf.PNG)
![img_7125](https://cloud.githubusercontent.com/assets/1407724/8049869/9bb71592-0e97-11e5-8c8c-a36ba69bccce.PNG)

**Comment by hackiftekhar** [comment]
Showing/hiding table section header is managed by the UITableView and not by library. It also have some default functionality to stick on top, and this can not be manipulated by library, so one option is for you to do some tweak by subclassing UITableView, and second option is to use Group tableView instead of Plain Table.
