### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by michellezi** [hackiftekhar/IQKeyboardManager#266]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IQKeyboardManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64

Does IQKeyboardManager support arm64?

**Comment by hackiftekhar** [comment]
IQKeyboardManager is available via source code and not via compiled library and not related to arm64 issue. It seems like you have may have some issues with your project settings.

**Comment by toohotz** [comment]
@hackiftekhar Not to thread hijack but do you have any plans to package the source code files into a framework? I personally did so with your source files for a cleaner setup for the Swift version as installing from the pod only gives me the Obj-C code.  If you're interested, I could show you in greater detail so that I'm not committing a robbery on this thread.

@michellezi are you by chance trying to run on device? If so then you'll have to look into the your provisioning profiles to see if you have it setup correctly for your project, it's not an issue related to the source code.

**Comment by hackiftekhar** [comment]
@toohotz Thanks for the great suggestion, as per my opinion if someone needs framework, then they should build it personally with source files. Suppose someone stuck with some scenarios/issue in their project due to library code logic, then source code help them to determine the reason of issue, but framework will not. So I would prefer to distribute with source code and leave developer to build framework if they need.
