### ISSUE TITLE
UItextView bug

### ISSUE THREAD

**Issue by wy19901227** [hackiftekhar/IQKeyboardManager#271]
when i add a UItextView, first I tap the textView,it can not adjust the frame, but second I tap the textView,
it can adjust the frame.  I do not konw why?

**Comment by wy19901227** [comment]
first the _textFieldView=nil, secont it is not nil,  why?

**Comment by wy19901227** [comment]
I have temporarily fix the bug in a bad way .
show the code
 int the adjustfram method

   if (!one) {
        one=YES;
        [self adjustFrame];
    }

what a strange bug.  I hope  you can  fix it.

**Comment by hackiftekhar** [comment]
Because of the Notficiation Mechanism.

For TextField, textField Notification methods get called first and then we get Keyboard Notification. In this case we have textField object.

For TextView, Keyboard Notification methods get called first and then textView Notification methods. In this case we don't have textView object when Keyboard Notification gets fired, so you are getting _textFieldView as nil.

**Comment by wy19901227** [comment]
so  how to resove it?

**Comment by wy19901227** [comment]
_commenTextView.keyboardDistanceFromTextField=50;  and  this  code  does not work

**Comment by hackiftekhar** [comment]
This is iOS limitation for me, and we all need to think about it to come-up with a solution.

**Comment by wy19901227** [comment]
In IOS5  ，there are two notification called UIKeyboardWillChangeFrameNotification and
UIKeyboardDidChangeFrameNotification, though test,these nitification are corect.So ,I think you can try fix it in this way.

**Comment by hackiftekhar** [comment]
I have some different set of tasks when keyboard is about to appear and when keyboard is about to dismiss. If I go with WillChangeFrame/DidChangeFrame then I must have to find-out it manually that the keyboard is about to appear or is about to dismiss, and that's why I'm scared of the changes.
