### ISSUE TITLE
Scrolls Up View on Textfield ResignFirstResponder

### ISSUE THREAD

**Issue by Piyush08** [hackiftekhar/IQKeyboardManager#284]
I am also facing the same problem.
I want to show picker view instead of keyboard, it works fine to show keyboard.
But when I try to show keyboard to other textfield then it pushup(scrolls up) the view to that textfield.

My code is as below:

-(BOOL)textFieldShouldBeginEditing:(UITextField *)textField
{      //This Method is called every textfield evenThough Delegate is assign for 2 textfields

    if(textField==txt_AnimalType || textField==txt_VehicleType)
    [textField resignFirstResponder];
    
    return YES;
}

-(void)textFieldDidBeginEditing:(UITextField *)textField
{
    [_pic_single reloadAllComponents];
    _pic_single.hidden=NO;
}

Note: I allow the delegate for only 2 textfields.

**Comment by hackiftekhar** [comment]
@Piyush08 Please share full demo project so that I can debug it.

**Comment by hackiftekhar** [comment]
Do you have any updates on this?

**Comment by hackiftekhar** [comment]
@Piyush08, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
