### ISSUE TITLE
Frame not moving correctly - swift 2.0

### ISSUE THREAD

**Issue by odedharth** [hackiftekhar/IQKeyboardManager#305]
Hi,

Just upgraded my project to Swift 2.0, and updated the pod to its latest version and it seems that now the keyboard is hiding the text field. 

![file 25-09-2015 2 58 17 pm](https://cloud.githubusercontent.com/assets/624023/10099820/f71fb12a-6395-11e5-96af-f32e471e84b3.png)

Podfile line:

    pod 'IQKeyboardManagerSwift'

Any idea why?
It used to work before the update

**Comment by hackiftekhar** [comment]
Read `Installation` section of read me file. From swift 1.2 you need to explicitly enable swift version.

**Comment by odedharth** [comment]
@hackiftekhar you mean adding this line: 

        IQKeyboardManager.sharedManager().enable = true

because I've added it...

**Comment by hackiftekhar** [comment]
yes, I mean by the above code.

**Comment by odedharth** [comment]
so it's not working

**Comment by acegreen** [comment]
I can confirm it doesn't work even with the code above.

**Comment by soggybag** [comment]
I just tried this with swift in Xcode 7 this morning and it worked for me.

I just made a demo project. I placed a bunch of text fields into the default view controller, dragged the IQKeyboardManagerSwift folder into my project, last I added the enabling code to app delegate. Code hints showed the IQKeyboardManager class, so my project recognized the added files.

**Comment by acegreen** [comment]
In my case he fields are in a UITableViewController. Can you confirm it works there too?

**Comment by soggybag** [comment]
I just tested this with a UITableViewController in storyboard. It seemed to be working. I didn't have any code attached to the tableview controller. I made it all in Storyboard, drag the IQKeyboardManagerSwift folder into my project, enabled it in app delegate, and it seemed to work. 

I used a mix of UITextFields and UITextViews in multiple sections in the tableview. 

If there was any problem, it seemed that the < and > keys wouldn't let me get to previous textfields if I clicked on TextView, I could go forward to the next TextView or TextField clicking >, but I could go to a textField or TextView before the first one I clicked by clicking <. 

This was just one fast test.

**Comment by acegreen** [comment]
Ok can you add me on Skype to demonstrate this really quickly?

Skype: aelalfy1989

**Comment by soggybag** [comment]
I posted the examples I used to github. 

https://github.com/soggybag/KeyboardAvoiding-Test
https://github.com/soggybag/MagicWeapon-Mockup

**Comment by acegreen** [comment]
Looked at MagicWeapon but can’t catch the difference

Just add me so we can sort this out for everyone once and for all

**Comment by acegreen** [comment]
Try this: https://dl.dropboxusercontent.com/u/8061535/MagicWeapon-Mockup-master.zip

**Comment by hackiftekhar** [comment]
FYI, UITableViewController already have their logic to move textField out of the way, library doesn't do anything for moving view only if textFields are inside UITableViewController.

**Comment by acegreen** [comment]
Take a look at the demo project I linked. On iPhone 4s, it doesn't move it.

**Comment by acegreen** [comment]
I thought this logic was there too but doesn't seem to work

**Comment by hackiftekhar** [comment]
I can see in demo project, and found that the static tableViewController is working fine but the dynamic one is not working properly.

**Comment by hackiftekhar** [comment]
Currently I'm following recommended approach:-

Apple says, UITableViewController is responsible for resizing and repositioning itself to show textField/textView. So library handles all other resizing and repositioning except UITableViewController(Because it's already handled by iOS). See notes here

https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

Note: The UITableViewController class automatically resizes and repositions its table view when there is in-line editing of text fields. See View Controllers and Navigation-Based Apps in Table View Programming Guide for iOS.

-----
So it may be apple bug. I would love to hear best solution from you guys.

**Comment by acegreen** [comment]
Dynamic also works but it's my implementation, so where in my classes code, it stops working

**Comment by acegreen** [comment]
So so so, I finally figured out what the issue is. In my UITableViewController class I implemented viewWilllAppear without doing   super.viewWillAppear(true)

Thats literally the one line of code that messed it up. Hope this helps the others

**Comment by hackiftekhar** [comment]
ohh, So writing super.viewWillAppear(true) works for you? Probably UITableViewController implemented something useful on viewWillAppear.

**Comment by acegreen** [comment]
Yup worked like a charm. UITableViewController has that auto scroll feature in it, but I was overwriting the viewWillAppear and not doing super, calling the issue. 

If you are using a UIViewController then thats different and we can probably chat about it on Skype if you need some help. Technically I shouldn’t be looking at this library, I just came across it because my UITableViewController didnt do what its suppose to.

**Comment by hackiftekhar** [comment]
I think your previous comments should be useful for others. Thanks for the help and figuring out the actual issue.

**Comment by basalphenaar** [comment]
Thanks so much for the super.ViewWillAppear() suggestion, saved me some hours of pointless struggling!

**Comment by riznyk7** [comment]
super.ViewWillAppear()  fkn amazing!!!!!
till now I will always call super methods, fuck that shit
