### ISSUE TITLE
Next/previous button doesn't detect hidden table cells with UITextFields

### ISSUE THREAD

**Issue by vortek** [hackiftekhar/IQKeyboardManager#340]
1. Create a UITableview with more cells than would fit on the screen. 
2. Add a UITextField to each one. 
3. Scroll down and select one UITextField
4. press Previous arrow, which gets disabled when it reaches the top visible field, ignoring the cells that are up and thus, not visible at that moment unless you scroll up first.

**Comment by hackiftekhar** [comment]
This limitation is due to tableView cell reusable logic.

**Comment by Shamsiddin** [comment]
I've just downloaded your demo example. and played around for UITableView and got the same problem. You said 

> this limitation is do to tableView cell reusable logic. 

Can you give solution how to fix it. Do we need to give unique cell identifier for each cell or what?

Thanks.

**Comment by hackiftekhar** [comment]
UITableView cell logic works different than it appears, UITableview remove cell from it self it cell goes above or below it's frame. So technically when cell isn't appearing then cell isn't in the view hierarchy. If you give a unique cell identifier then you could somehow optimise 70% to deal with the situation but it doesn't fix problem 100%.

**Comment by Janneman84** [comment]
I am using a static table view and I'm having the same problem. I have outlets of all my text fields. Can't I just set an array of textfield outlets somewhere? The up and down buttons then just have to traverse the array instead of the view hierarchy.

Or even a delegate method, something like
indexPathOfPreviousButtonOfTextField:UITextField at IndexPath: indexPath -> IndexPath
for use with tables of course. It just returns an IndexPath so the button nows it can find something there. When the button is tapped it scrolls to that cell and then looks for a text field/view.

Either would give you more control of the order too.

**Comment by hackiftekhar** [comment]
You can change `toolbarManageBehaviour` property to find textfields sorted by tags. For more please check documentation.

**Comment by Janneman84** [comment]
I added `IQKeyboardManager.sharedManager().toolbarManageBehaviour = .byTag` and changed the tags of the text fields to force a different order, but it didn't work. Yes the text fields were all on screen.

Either way this won't fix the problem with tables now will it?

**Comment by dineshnagarajandev** [comment]
Is there any solution for this issue with the UITableView cell.

I'm also facing the same issue and from bottom to top it's navigating properly between the text fields but with the Top and Down facing issue for cells that are not visible.
