### ISSUE TITLE
IQKeyboardmangerswift warning Xcode 7.1

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#349]
![screen shot 2015-11-05 at 4 55 27 pm](https://cloud.githubusercontent.com/assets/6657591/10967107/3e469466-83de-11e5-90b4-1d7861c57866.png)

can we get rid of with this warnings ? any workaround ?

**Comment by hackiftekhar** [comment]
It's because minimum iOS version for  Swift library is iOS7, and you are building with iOS8 as minimum deployment target. It's not good for library to drop support for lower iOS version. Regarding your question about any workaround, I don't see anything in swift, by which we can skip some code compilation, like we have in C language "#if #endif"

**Comment by hackiftekhar** [comment]
Closed in favour of #352 because there is more specific issue title regarding this issue.
