### ISSUE TITLE
Maybe you should consider topController.childViewControllers

### ISSUE THREAD

**Issue by guodong10518** [hackiftekhar/IQKeyboardManager#359]
In IQUIView+Hierarchy.m, I think following codes should be added below line 100:
[controllersHierarchy addObjectsFromArray:topController.childViewControllers];

Because topController = self.window.rootViewController;, topController may be just an instance of normal UIViewController. And it adds child viewcontroller(e.g. UINavigationController or UITabbarViewController). 

If what I considered was right, please tell me the result by sending email: wangguodong@ihidea.com. Thank you!

**Comment by hackiftekhar** [comment]
That's because there is a valid reason behind this. Library should only move (up-down) the top most controller's view which is showing on screen. If there are any child view controller added within the top most controller, then child view controller's view is considered as normal UIView added to the top most controller's view and is treated normally. So each time the top most controller's view is moved regardless of it's child view controller's view.

**Comment by guodong10518** [comment]
Thanks for your reply. 
In your demo, the navigation bar will be moved outside the visible screen. And what I want is that the navigation bar stays at top of screen, and the content view will moved up. I think it is better. And in my opinion, maybe the method named"topMostController" in IQUIView+Hierarchy.m could be modified.

**Comment by hackiftekhar** [comment]
There is a trick to keep navigation bar static. Please check read me.
