### ISSUE TITLE
IQKeyBoardManager bug demo

### ISSUE THREAD

**Issue by new-soul** [hackiftekhar/IQKeyboardManager#362]
when I use in my project,I find a bug.
A UIView with several input views,some time it will trigger all input views at the same time.More obviously,it contain a textField to show pickerView.

And I create a simple demo to show the bug on https://github.com/new-soul/IQKeyBoardManagerBugShowdemo.git
If you remove the IQKeyBoardManager,that will ok.

**Comment by hackiftekhar** [comment]
You should protect your logical code by `isAskingCanBecomeFirstResponder` property in `textFieldShouldBeginEditing` method.

Something like this in your code
```
    if (textField == self.typeField) {
        
        if ([textField isAskingCanBecomeFirstResponder] == NO)
        {
            [self endEditing:YES];
            
            pickTypeView *pick = [pickTypeView pickView];
            .......
            .......
        }

        return YES;
   }
```

Please check read me file for more information about `isAskingCanBecomeFirstResponder`.

**Comment by hackiftekhar** [comment]
@new-soul, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
