### ISSUE TITLE
Previous button shows as disable(grey) even more textfield in previous cell

### ISSUE THREAD

**Issue by maninp** [hackiftekhar/IQKeyboardManager#365]
Textfield is in tableview cell(custom cell). I'm using UITableViewController. Next/Previous is working perfectly for visible cells. Assuming currently we have 10 cells and cursor on 1st textfield, now we moved into 10th textfield by tapping next. Now we could moved to previous cell's upto 5th, When we reach 5th textfield, previous button will show as disabled. ie first four cells are not visible in this page. How could I resolve this issue?

**Comment by hackiftekhar** [comment]
It's an iOS limitation because iOS uses cell reusability concept for drawing it's tableView. For library it's hard to determine when a new cell is added at the end or at the beginning of tableView. That's why I'm not able to resolve this issue.

**Comment by maninp** [comment]
Yes. I could understand. Is there any workaround for this?

My thought:
While we play previous, if we keep previous cell as visible(by scroll to or setting content offset), then we could do this. Right? Could you detect that there's more cell in top(if we provide datasource count as total number  of cell which has textfield)? ie if we provide datasource count, you will know how many cell's will show textfield and also could detect where we are(in which cell). that means. If we are in second cell, you could show first cell by scrolling. 

Note: If cells are in different size and large, we couldn't do this. any way I think, you could do that.

**Comment by hackiftekhar** [comment]
But we have to ask from viewController via some mechanism like delegates. But I love automatic things like "Do not irritate users by asking something, just observe the things and think what user wants".

**Comment by maninp** [comment]
If you could do this, you could provide it as optional delegate. Instead of ignore, you could think this because it's very common use case. If it is very rare, we may leave as it is. 

If you'll allow, in future somebody will code for this. :+1:

**Comment by hackiftekhar** [comment]
It's a common case, but there are some difficulties with UITableView. UITableView uses the concept of reusing the cell and removing hidden cells  from the view. That's why it can't be fixed.

According to our situations/requirement and Apples implementation of UITableView, there are difficulties. Technically how can I find the position of a cell which is not in view hierarchy(removed by UITableView from it's hierarchy and put it in UITableView cell cache pool).

Closing this issue in favour of the iOS limitations, which is not able to patch by some easy logic.
