### ISSUE TITLE
UITextView inside UIView clipped by keyboard

### ISSUE THREAD

**Issue by Emailrus** [hackiftekhar/IQKeyboardManager#375]
Hi,

Not sure if I have correct setup, but I'm not sure what to do with cases, when my view is defined in xib file and UITextView has bottom constraint to superview. In this case UITextView got covered by keyboard pretty badly. Here is the [example](https://github.com/Emailrus/IQKeyboardManagerTesting).

Sorry if this problem was already discussed, but the closest one I could find was [this](https://github.com/hackiftekhar/IQKeyboardManager/issues/358)
Also as a side note, there is no reaction on offset when I open/close keyboard suggestion panel.

Thank you

**Comment by hackiftekhar** [comment]
I checked the sample and found that the library can't do something for you with particularly in your case.
Technically you've pinned all side constraint with superview (You said that "Keep this distance from superview"), and your UITextView side is too big.

IQKeyboardManager tried to fit your UITextView in the visible area but unable to do so, because the size of UITextView is big.

The only way for you to adopt storyboard and pin bottom constraint with Bottom Layout Guide and then map that constraint with IQLayoutGuideConstraint. That way you can restore the size of your textView upon keyboard show/hide.
