### ISSUE TITLE
Errors：Value of type 'UIScrollView' has no member 'shouldRestoreScrollViewContentOffset'

### ISSUE THREAD

**Issue by senglez** [hackiftekhar/IQKeyboardManager#414]
When I drop it into my project , it has 3 errors in IQKeyboardManager.swift : 

My Xcode‘s version is 7.2 

Please tell me how to fix it.Thanks.

**Comment by hackiftekhar** [comment]
I tried to write something like
    scrollViewDemo.shouldRestoreScrollViewContentOffset = true;
in demo project and demo compiles successfully. Are you sure you are using latest code?

**Comment by senglez** [comment]
Hi hackiftekhar , I pulled the latest code.
The error code is like this : 
if lastScrollView.shouldRestoreScrollViewContentOffset == true {  //this is the error 
       lastScrollView.contentOffset = self._startingContentOffset
}

**Comment by hackiftekhar** [comment]
Are you using carthage?

**Comment by beseder42** [comment]
Was the same for me.

Solution: If you include IQKeyboardManager by copying the source code into your proejct and used any earlier version you might have just replaced the old code with the new version. Then, since this file is new, you need to add `IQUIScrollView+Additions.swift` to your project manually.

In any other case, check if the file is included in your project, since it seems to be missing.

**Comment by senglez** [comment]
Hi beseder42 ,Thank u. Its working now , just using your method.

**Comment by hackiftekhar** [comment]
It is fixed with 3.3.7 on carthage.
