### ISSUE TITLE
Can your manager work not only with text field or view?

### ISSUE THREAD

**Issue by andrewSvsg** [hackiftekhar/IQKeyboardManager#461]

**Comment by andrewSvsg** [comment]
I created custom control
And control use  own inputView and inputAccessoryView
but they hide control when appear

**Comment by hackiftekhar** [comment]
If you have any custom inoutView or inputAccessoryView then IQKeyboardManager doesn't override your custom settings. I would guess your custom control should work properly. If not then this may be our mistake, if not then figure out the problem and let me know.

**Comment by andrewSvsg** [comment]
My custom control have base class UILabel not UITextField or UITextView
Maybe I need to implement some protocol and IQKeyboardManager will track my control?

**Comment by hackiftekhar** [comment]
If it's like UITextField/UITextView then you could use `registerTextFieldViewClass:didBeginEditingNotificationName:didEndEditingNotificationName` method to register your object with **Objective-C** version of library. It's not fully supported with Swift version because there are some complexities with **Swift Strong Typecasting**.

**Comment by CavalcanteLeo** [comment]
@hackiftekhar i have tried to register this method inside UIViewController and my custom UIView, and both haven't worked

Is there any exemple?

Thanks in advance.
Leo
