### ISSUE TITLE
Adding framework package

### ISSUE THREAD

**Issue by RomanVolkov** [hackiftekhar/IQKeyboardManager#539]
When I compile the project from sources and D&D .framework to my project U got crash on starting the app. Some of the images are missing. How I can solve this?
I want to use compiled version of your library and do not include source files

**Comment by hackiftekhar** [comment]
You can use CocoaPods if you can or you can use Carthage if you want to include compiled version of library.

**Comment by RomanVolkov** [comment]
Yeah. But what If I'm not using CocoaPods. They have some bugs.

**Comment by hackiftekhar** [comment]
Btw you are compiling dynamic version of framework. You should compile a static version. You can search on stackoverdlow about "dylib Image Not Found" issue and I'm sure you'll find something useful. However closing this issue because it's a developer choice to compile library code to a framework and it's not much related to library issues.

**Comment by RomanVolkov** [comment]
Thanks for the reference about static version. I guess it's what I needed
