### ISSUE TITLE
Click Return key in keyboard does not dismiss nor go to next textField

### ISSUE THREAD

**Issue by ZeranLatte** [hackiftekhar/IQKeyboardManager#570]
Using Xcode 7.3 Swift 2.2
<img width="651" alt="screen shot 2016-07-15 at 13 01 43" src="https://cloud.githubusercontent.com/assets/10468849/16887072/cbbefeb2-4a8c-11e6-801a-58398520531c.png">

Set a breakpoint here (IQKeyBoardReturnKeyHandler.swift) but it was not caught. Guess the ReturnKey handler not enabled?
The left/right arrow and "Done" work great.

**Comment by t-unit** [comment]
Having the exact same issue. Problem also exist in the Demo application (both DemoSwift & DemoObjC).

**Comment by hackiftekhar** [comment]
Please check manual management doc to know how to use IQKeyboardReturnKeyHandler.

**Comment by t-unit** [comment]
Ok thanks for clarifying. 

I'll add a `IQKeyboardReturnKeyHandler` to each view controller requiring keyboard handling.
(fare well *No More Manual Work* &  *No More #imports* 😉)

**Comment by hackiftekhar** [comment]
@t-unit In most of the cases *Library is Codeless*. But for return key handling, there is no easy way to know when user taps on return key. We can only know via it's delegate and you know that library cannot override user's set delegate because it could lead to many issues. This is why developer needs to do extra work if they want to handle Return Key too.

If you don't implement `IQKeyboardReturnKeyHandler` then you are still good to go to dismiss with `Toolbar done button`. *No More Manual Work & No More #imports*.

It's upon developer to use it or not :).

**Comment by t-unit** [comment]
@hackiftekhar  Not to bitch about your work. In fact I think this project does its job very well! You just promise a bit more than you can deliver in the end. `**CODELESS**, Zero Line Of Code` is simply only true in some cases. (IMHO having working return keys is pretty important.)

But overall thanks for providing us with this project, maintaining it and responding so quickly!

**Comment by hackiftekhar** [comment]
@t-unit `Codeless` is true in most of the cases. It means that Just Drag and Drop  or just do `pod install` it will work for sure.

But all of us have different requirements, so if developers wants to customise it according to their requirement then surely it isn't `codeless` for them.

Now I think I can do something better with `UIControlEventEditingDidEndOnExit` control event and will understand how it works with return key.

@t-unit thanks for your great feedback!

**Comment by ZeranLatte** [comment]
@hackiftekhar Thanks a lot.
