### ISSUE TITLE
swift - disable for specific view controller

### ISSUE THREAD

**Issue by karnakar** [hackiftekhar/IQKeyboardManager#572]
Thanks for the awesome library, I tried to disable for specific view controller, as per the doc i tried "disableInViewControllerClass" method, but it is not available in v 4.0.0, i updated the pod file (v 4.0.4) but still I'm unable to see the method in the class "IQKeyboardManager". Can you help this to sort out.

**Comment by hackiftekhar** [comment]
This is replaced by `disabledDistanceHandlingClasses` NSMutableSet property

**Comment by karnakar** [comment]
will this return disabledDistanceHandlingClasses or set the classes, i want to disable for one view controller

**Comment by hackiftekhar** [comment]
you can add your controller class to this NSMutableSet.

**Comment by al-esok** [comment]
Hello,

Can you please tell me if there is a way to disable the keyboard manager on a specific subclass of UIViewController?

The thing is that I have 3 layers of subclasses of UIViewController and I think that the reason why I am still seeing the IQKeyboard on that uiviewcontroller subclass is because of the check isKindOf UIViewController.

Can you please suggest me how should I proceed in this case?
Thanks,
Avinash

**Comment by hackiftekhar** [comment]
Please read this issue carefully or read tge manual management guide, the answer is already posted here.

**Comment by al-esok** [comment]
Hello,

Yes you are right.  I did not use the correct version of the pod.

Thanks for the great work :)

Kind Regards,
Avinash
