### ISSUE TITLE
 Method of textField's delegate call exception

### ISSUE THREAD

**Issue by lc081200** [hackiftekhar/IQKeyboardManager#590]
Dear master：
I created a lot of input textField.   I want to show A alertView when some of these textField begin editing. But all of these textField  will run  the method of "-(BOOL)textFieldShouldBeginEditing".

And when I touch other position current textField, It will run  method of "- (void)textFieldDidBeginEditing:(UITextField *)textField".

**Comment by hackiftekhar** [comment]
You should read Manual Management guidelines. There are something useful for your problem.

**Comment by hackiftekhar** [comment]
You can find the link of documentation in Read me file.

**Comment by hackiftekhar** [comment]
@lc081200, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
