### ISSUE TITLE
can't see Next and Previous button

### ISSUE THREAD

**Issue by davidgloves** [hackiftekhar/IQKeyboardManager#591]
I wrapped UITextField in UIView, which maybe caused this issue. How can I get solve this. I do need wrap the textfield in UIView.
this is the demo.[keyboardDemo](https://github.com/davidgloves/keyboardDemo/archive/master.zip)

**Comment by hackiftekhar** [comment]
Ok, will check your demo.

**Comment by hackiftekhar** [comment]
@davidgloves This is because your TextFields are not direct siblings. You have added both textFields in differentView i.e. LoginField->CCTextField->UITextField. Next/Previous only works with direct siblings. For a tweak you can read `Show Previous/Next arrow buttons for textField which are not direct disblings` section here https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md
