### ISSUE TITLE
Keyboard is not dismissing while showing popup

### ISSUE THREAD

**Issue by ibhavin** [hackiftekhar/IQKeyboardManager#594]
@hackiftekhar 

I have multiple textfield in my tableview so, I have give unique tag to it. Some of textfield requires keyboard for input, some of require pickerview and some requires popup.

Here is my screen:
![simulator screen shot 03-aug-2016 12 41 27 pm](https://cloud.githubusercontent.com/assets/16459948/17356727/aa56d616-5976-11e6-850d-8cb6fb159ab8.png)

I don't want to show keyboard on textfield (4). So, I have override my Textfield delegate method to this:

```
- (void)textFieldDidBeginEditing:(UITextField *)textField
{
    PopUpView *popup = [self.storyboard instantiateViewControllerWithIdentifier:@"PopUpView"];
    
    if (textField.tag==4) {
        
        [[IQKeyboardManager sharedManager]resignFirstResponder];
        [textField resignFirstResponder];
        [self.view endEditing:YES];
        self.providesPresentationContextTransitionStyle = YES;
        self.definesPresentationContext = YES;
        [popup setModalPresentationStyle:UIModalPresentationOverCurrentContext];
        [self presentViewController:popup animated:YES completion:nil];
    }
}
```
It woks when I click direct on textfield(4). But when I first click on textfiled(3) or other textfield which input view is keyboard and after that I click on textfield(4) (_without pressing Return key_) keyboard is not dismissing and return key is also not working.

![simulator screen shot 03-aug-2016 12 51 41 pm](https://cloud.githubusercontent.com/assets/16459948/17356901/9b588a5a-5977-11e6-9e06-ff049f60c7c9.png)

Tell me if you want more information.

**Comment by hackiftekhar** [comment]
You could take a look at the Manual Management Doc, there are some useful information regarding textFieldShouldBeginEditing delegate method.

**Comment by ibhavin** [comment]
@hackiftekhar

 Thanks for pointing out that. [textFieldShouldBeginEditing in Manual Management Doc](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#doing-custom-work-on-textfield-with-returning-no-in-textfieldshouldbeginediting-delegate) helped me.

**Comment by hackiftekhar** [comment]
@ibhavin, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.

**Comment by rushita10** [comment]
@hackiftekhar  I am facing the same issue mention above. I am using IQKeyboardManagerSwift and I tried to dismiss the keyboard using 
IQKeyboardManager.shared.resignFirstResponder()
 self.view.endEditing(true) 

in textFieldShouldBeginEditing.I am attaching my whole method below - 

func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        if textField == textFieldGender {
            IQKeyboardManager.shared.resignFirstResponder()
            self.view.endEditing(true)
            var currentIndex = 0
            
            for index in 0...(arrayGender.count - 1) {
                if arrayGender[index] == textField.text {
                    currentIndex = index
                }
            }
            CustomPicker.showCustomPicker(title: StringConstant.select_gender.localized(), currentSelectedIndex: currentIndex, arrOptions: arrayGender) { (success, index) in
                if success ?? false {
                    textField.text = self.arrayGender[index ?? 0]
                }
            }
            return false
        }
        return true
    }

**Comment by hackiftekhar** [comment]
Remove these lines since they make no sense to me in the method.

IQKeyboardManager.shared.resignFirstResponder()
           self.view.endEditing(true)

**Comment by rushita10** [comment]
Then what I can implement instead of that. I need to down the keyboard when my pickerview open. But due to this issue, I am not able to achieve my task. Can you help me out.
