### ISSUE TITLE
Framework file

### ISSUE THREAD

**Issue by ufoloko** [hackiftekhar/IQKeyboardManager#613]
Please add framework file to add to project, it could be great

**Comment by hackiftekhar** [comment]
I think it should be a developer requirement. I was hosting framework files before 1 year but then I removed it because it was taking unnecessary development time to rebuild framework after each updates. Now a days most us use cocoapods or carthage to add it as dependency which would easy our task and reduce requirement of hosting framework file. I would love to hear from you in this.

**Comment by ufoloko** [comment]
Thanks for your response

I'm relatively new in iOS development but if you can guide me on how to generate framework file I can help you with that task.

The reason to prefer use framework file is for clean code, having all the files into our projects is not a good practice in our company because we don't want our developers have access to modify thirty party components. 

From now I will try to help your with feedback, your component is awesome.

Thanks 

Paul Calderon

**Comment by hackiftekhar** [comment]
Here is the clean tutorial I found to make a framework http://locomoviles.com/uncategorized/create-ios-cocoa-touch-framework-using-xcode/
