### ISSUE TITLE
textFieldShouldBeginEditing not called

### ISSUE THREAD

**Issue by wojczitsu** [hackiftekhar/IQKeyboardManager#615]
In my UITableViewCell subclass:

    -(BOOL)textFieldShouldBeginEditing:(UITextField *)textField{
    if (textField.isAskingCanBecomeFirstResponder == YES){
        NSLog(@"A");
        return YES;
    }
    NSLog(@"B");
    return NO;
    }
I've got few UITextFields in one UITableViewCell. 
Steps:
1. I touch textfield in first cell - B gets called by delegate and then A gets called by manager (CORRECT)
2. Then I touch textfield in another cell, and then again in first one - just A gets called by manager, there is no B call by my delegate. (INCORRECT)

**Comment by hackiftekhar** [comment]
I think you should debug your code to check if your delegate is properly set.

**Comment by wojczitsu** [comment]
It is properly set. If I remove plugin from project, everything works as expected.

**Comment by hackiftekhar** [comment]
Are you using IQKeyboardReturnKeyHandler in that class?

**Comment by rs10693** [comment]
In my case "textFieldShouldBeginEditing" call multiple time.

**Comment by hackiftekhar** [comment]
@rs10693 Please check Manual Management guide for more help on this, if you still got issue then please share some more details.

**Comment by rs10693** [comment]
I have follow your step like given action method but doesn't call. See below i have mention some of code snippet.

    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
            textField.delegate = self
            cell?.contentView.addSubview(textField)
            textField.addTarget(self, action: #selector(textFieldAction(_:)) , forControlEvents: .TouchUpInside)
}

func textFieldShouldBeginEditing(textField: UITextField) -> Bool {
        return true
    }
    func textFieldAction(textField: UITextField){
        print("Rushabh")
    }

plz. suggest if i am wrong.

**Comment by hackiftekhar** [comment]
@rs10693 can you share any demo project to debug it?

**Comment by rs10693** [comment]
@hackiftekhar Now it's solved.

**Comment by hackiftekhar** [comment]
@rs10693 how it is solved?

**Comment by rs10693** [comment]
@hackiftekhar  In my case we open action sheet on textfield but right now i am replace button.

**Comment by hackiftekhar** [comment]
ok, so you did a UI change to solve your problem.

**Comment by hackiftekhar** [comment]
@all, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
