### ISSUE TITLE
textField in scrollView will always response the “ textFieldShouldBeginEditing” With IQKeyboardManger Swift 4.0.4

### ISSUE THREAD

**Issue by HeMiaoAmy** [hackiftekhar/IQKeyboardManager#620]
in an  viewcontroller ,I set many textFields in scrollview ,and set delegates.
i find all textfield will resopnse this delegate function "textFieldShouldBeginEditing",even I set if conditional 
eg:
 func textFieldShouldBeginEditing(textField: UITextField) -> Bool {
        if textField == first {
            print("first")
            return false
        } else if textField == second {
            print("second")
            return false
        }
        return true
    }

when I click the textfield called third,It will print "second " "first"
wish you can help me with this problem.thanks,

**Comment by hackiftekhar** [comment]
Please read Manual Management guidelines about textFieldShouldBeginEditing method.

**Comment by s1Moinuddin** [comment]
Manual Management guidelines don't solve the problem. As, 
-(BOOL)textFieldShouldBeginEditing:(UITextField *)textField {   
 if (textField == customTextField)
    { return NO; }
    else 
    { return YES;}
}

Always returns no for any TesxtField, I mean  (textField == customTextField) always true no matter which text field you select. I also Tried by adding Tag to different UITextFields, but unfortunately it adds the same tag for All textFields. Same thing goes for delegate. if You add a delegate for one textField, All the textField calls the delegate method. 

Note: Bellow 3 images should make it clear.. I'm manually using IQKeyboardManagerSwift. In my viewController I've several UITextFields in a scroll view. Badly looking for a solution.
![screen shot 2016-09-01 at 7 58 34 pm](https://cloud.githubusercontent.com/assets/10473280/18170410/0ebe3e3a-7080-11e6-864d-92eddc3d44ec.png)
![screen shot 2016-09-01 at 8 03 21 pm](https://cloud.githubusercontent.com/assets/10473280/18170417/17d99bcc-7080-11e6-9044-1b3f9913046b.png)
![screen shot 2016-09-01 at 8 07 35 pm](https://cloud.githubusercontent.com/assets/10473280/18170418/1814c77e-7080-11e6-9009-4e99d83da40d.png)

**Comment by hackiftekhar** [comment]
@HeMiaoAmy @s1Moinuddin I believe you haven't read Manual Management guide carefully, there are two proposed solutions and you only read half part of the first solution.

**Comment by s1Moinuddin** [comment]
My bad... I was thinking in wrong way... It do solves the problem...

**Comment by hackiftekhar** [comment]
@all, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
