### ISSUE TITLE
textFieldShouldBeginEditing loading every textfield in tableview 

### ISSUE THREAD

**Issue by kevinonik** [hackiftekhar/IQKeyboardManager#628]
I have a actionsheet picker that needs to be called when certain textfields are tapped. It is now conflicting with IQKeyboard .. 

` 
       func textFieldShouldReturn(textField: UITextField) -> Bool {
     
        
        if textField.tag == 6 {
            textField.resignFirstResponder()

        }
        else{
            IQKeyboardManager.sharedManager().goNext()
        }
        return true
    }
    
    func textFieldShouldBeginEditing(textField: UITextField) -> Bool {
        
        if textField.tag == 5 || textField.tag == 6{
            textField.resignFirstResponder()

            showPicker()
            
            return false
        }
        else{
        
        return true
        }
    }
    
    func showPicker() -> Void{
        
        self.superview?.endEditing(true)

        ActionSheetStringPicker.showPickerWithTitle("Choose Category", rows: ["Lab Manager", "Doctor", "Surgeon"], initialSelection: 1, doneBlock: {
            picker, value, index in
            
            print("value = \(value)")
            
            
            
            return
            }, cancelBlock: { ActionStringCancelBlock in
                
                
                return }, origin: self.txttextField)
        
        
    }
`
As you can see I have properly tagged every textfield but when i tap on a textfield it loads all the textfields and even if i tap on the textfield having tag other than 5 or 6 it still opens the picker
@hackiftekhar Help

**Comment by kevinonik** [comment]
never mind i did the other way around using tap gesture

**Comment by hackiftekhar** [comment]
@kevinonik, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.
