### ISSUE TITLE
why disabled in UITableViewController 

### ISSUE THREAD

**Issue by kocakmstf** [hackiftekhar/IQKeyboardManager#679]
Thanks for the library. It saved lots of time. 
I have a question. Why you disabled it in UITableViewController? Is it has a proper reason?

**Comment by hackiftekhar** [comment]
Because UITableViewController has their own mechanism for moving content above keyboard. For more info please look here:-

https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

You could also read previous issues
https://github.com/hackiftekhar/IQKeyboardManager/issues/37
https://github.com/hackiftekhar/IQKeyboardManager/issues/507
and there are more if you search `UITableViewController` in repo.

**Comment by kocakmstf** [comment]
Ty. In my case it didn't handle. So I replaced your code. I hope it works just like now

**Comment by hackiftekhar** [comment]
Hmm sometimes `UITableViewController` doesn't handle the situation well, but sometimes it does. But if I already tried to allow `UITableViewController` but then it was conflicting with `IQKeyboardManager` logic that's why I disabled that one.

Btw either you can change my code, and if you are using cocoapods then you can remove `UITableViewController` class from `disabledDistanceHandlingClasses` NSMutableSet in appDelegate since it's stored in that one only and removing that class should also work for you.

**Comment by tangqi92** [comment]
@hackiftekhar Thanks for the library!
I have a question, I have a `UITableViewController ` and I want to completely disabled the library.
And I tried to  use the method
```objective-c
[[IQKeyboardManager sharedManager].disabledDistanceHandlingClasses addObject:[UITableViewController class]];
[[IQKeyboardManager sharedManager].disabledToolbarClasses addObject:[UITableViewController class]];
[[IQKeyboardManager sharedManager].disabledTouchResignedClasses addObject:[UITableViewController class]];  
```
in my AppDelegate, and when I edit the textfield in UITableViewController, the keyboard will first appears, then disappear.Look forward to the reply~

**Comment by kocakmstf** [comment]
When I checked for the source code, in uitableviewcontroller, it disables otomatically. You don't need to disable again. I suggest you to remove these codes and check your other handlers. They should be doing it. Maybe you just reload tableview at the background etc. This is my opinion, we may wait for the op's answer :)

**Comment by hackiftekhar** [comment]
It's already disable for distance handling, but you have to explicitly disable for other things like you were doing.

Regarding the issue you are facing, it looks like due to your own code. Please check your code and make sure this issue isn't due to your own code.

**Comment by tangqi92** [comment]
I have checked my code, and that's my problem, i reload tableview at somewhere. Thx for your answer :)
@kocakmstf @hackiftekhar
