### ISSUE TITLE
canBecomeFirstResponder causes calling of textFieldShouldBeginEditing

### ISSUE THREAD

**Issue by hasangyulyustan** [hackiftekhar/IQKeyboardManager#709]
canBecomeFirstResponder in function _IQcanBecomeFirstResponder causes calling of textFieldShouldBeginEditing for all textfields in my uiview. Is this a known issue?

**Comment by hackiftekhar** [comment]
Yes, it's a known issue, please read manual management guide for workarounds.

**Comment by hackiftekhar** [comment]
@hasangyulyustan, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so `textFieldShouldBeginEditing` delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.

**Comment by navisingh** [comment]
It is unclear what legacy users are supposed to do when migrating from 4,0.9 to 4.0.13 w.r.t isAskingCanBecomeFirstResponder.  I would really appreciate you explaining the above.

**Comment by hackiftekhar** [comment]
You should just remove validation of isAskingCanBecomeFirstResponder. it will work fine since textfield delegate methods will no longer called multiple times.

**Comment by usuf1990** [comment]
Hi,
It's still calling delegate multiple times. I have a textfield inside UITableViewCell

**Comment by hackiftekhar** [comment]
Which version of library you are using @usuf1990 ?

**Comment by usuf1990** [comment]
@hackiftekhar   IQKeyboardManagerSwift (5.0.2)

**Comment by hackiftekhar** [comment]
I don’t think this method will be called multiple times from library. Can you please check again and sure the library calls this method multiple times.

**Comment by usuf1990** [comment]
@hackiftekhar It's called whenever I try to do next from input accessory view arrow

**Comment by hackiftekhar** [comment]
Can you please send me call stack so that I can understand from where your method is calling multiple times?

**Comment by usuf1990** [comment]
![screen shot 2017-10-02 at 10 46 59 am](https://user-images.githubusercontent.com/5227891/31086297-1a89b9d0-a75f-11e7-9f64-af71c523db23.png)
@hackiftekhar

**Comment by usuf1990** [comment]
@hackiftekhar  - Does it help?

**Comment by hackiftekhar** [comment]
Yup, it does help, you are getting this because your previous textField refused to become first responder. Because you probably return NO for a your next textField in textFieldShouldBeginEditing method. Am I right?

**Comment by usuf1990** [comment]
@hackiftekhar  yes! I wanted to open a popup for the new textfield

**Comment by hackiftekhar** [comment]
Then you should explicitly endsEditing:YES when you want to show popup. Can you please check if you can do that?
