### ISSUE TITLE
Disable UITextField autoscroll, if textfield is fully visible

### ISSUE THREAD

**Issue by Otbivnoe** [hackiftekhar/IQKeyboardManager#713]
Is there solution for disabling `UITextField'`s autoscroll if all textfield area is visible? Some magnetic property, I don't know.

**Comment by hackiftekhar** [comment]
If a textField is fully visible then library doesn't scroll textField. However there is a property something like `keyboardDistanceFromTextField` which defaults to 10. So you may try to set it to 0. Let me know if I misunderstood the question.

**Comment by sw-tt-harishmistry** [comment]
Yes, i think you are misunderstanding the question for example if i have iPhone 7 and i have scroll view with 20 textfield and i am on 20th textfield, then the topmost visible textfield is 11th one now when i directly tap on 11th textfield it scrolls down from top to just above keyboard which is wrong, it should not happen. Please check the snaps i have attached.
![1](https://user-images.githubusercontent.com/22932055/29113985-706e9b8c-7d10-11e7-9f9d-e285b20de74b.png)
![2](https://user-images.githubusercontent.com/22932055/29113984-706e1824-7d10-11e7-8148-34aa45306e66.png)

**Comment by hackiftekhar** [comment]
@sw-tt-harishmistry @Otbivnoe question doesn't clear if he is having UIScrollView or UIView as superview configuration, so I assume that he is having UIView as superview and provided my answer with that context. However there is no solution for now if it's superview is kind of UIScrollView.

**Comment by g3ntleman** [comment]
I have the same problem. My UITextFields are embedded in a scrollview. When I tap a bottom field, everything happens nicely: The Scrollview is adjusted to show the bottom field 10 picas above the keyboard.

However, if I subsequently tap into the text field right above, which is fully visible, the scrollview content is unnecessarily scrolled down under my finger, obscuring the bottom field.

My expected behavior is the IQKeyboardManager checks, if the frame of the TextField (-10 picas picas vertical inset) is fully visible (e.g. using -scrollRectToVisible:animated) and so does NOTHING in above case, because the text field is already fully visible. No need to scroll.
