### ISSUE TITLE
UITextView in UITableviewController small issue

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#79]
I have Downloaded the new Demo All Working great No issues yet.
But in UITableViewcontroller Example if i enter first time and select the UITextView the Problem is:
![ios simulator screen shot 29-sep-2014 12 41 42 pm](https://cloud.githubusercontent.com/assets/6657591/4438206/981c27b2-47a8-11e4-8f70-8fb5002fc682.png)
But if i Click Done and again Select UITextView the Behavior is Perfect like this :
![ios simulator screen shot 29-sep-2014 12 41 54 pm](https://cloud.githubusercontent.com/assets/6657591/4438214/cccebc54-47a8-11e4-85bc-cda1b0383032.png)

**Comment by hackiftekhar** [comment]
Closing issue, because in this case, UITableViewController is responsible to reposition scrollView ContentOffset.

Note: The UITableViewController class automatically resizes and repositions its table view when there is in-line editing of text fields.

//See notes:- https://developer.apple.com/Library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html.
