### ISSUE TITLE
Disabling with IQKeyboardManager.sharedManager().enable doesn't work

### ISSUE THREAD

**Issue by pilot34** [hackiftekhar/IQKeyboardManager#829]
I use `IQKeyboardManager` only on one ViewController, I do 
`IQKeyboardManager.sharedManager().enable = true`  in viewWillAppear and 
`IQKeyboardManager.sharedManager().enable = false` in viewWillDisappear. 

But on another screen `IQKeyboardManager` handles textFieldDidBeginEditing notifications and I have bugs related to https://github.com/hackiftekhar/IQKeyboardManager/issues/88

Should it work so or is it a bug? In my opinion when you disabling IQKeyboardManager it should unsubscribe from all notifications and shouldn't work at all until it will be enabled later.

I attached small example project, when I  enabling and disabling IQKeyboardManager, but it shows toolbar and handles notifications after disabling.

[TestIQKeyboardManager.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/947863/TestIQKeyboardManager.zip)

**Comment by alfonzm** [comment]
Have you tried using the `enabledDistanceHandlingClasses` property? Check out the documentation: https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#enabledisable-distance-handling-between-different-viewcontrollers

**Comment by pilot34** [comment]
@alfonzm  `enabledDistanceHandlingClasses` won't disable anything better than `enable = false` property:
![](https://monosnap.com/file/IfO8w4wbDGJ7CwZNE6o5AnJCOtbE4J.png)

I want to say that if I turn off the library with `enable = false`, I expect that it will not intercept any of my app's notifications and change app's behaviour. But in current API when `enabledDistanceHandlingClasses` has higher priority then `enable` it can't be done..

Maybe it will be fixed when `IQKeyboardManager` won't call `canBecomeActive` in the next version..

**Comment by kmcgill88** [comment]
@pilot34 I'm in the same position as you. Have you found a work around?

**Comment by kmcgill88** [comment]
@pilot34 - @alfonzm I forked and made a [couple of changes](https://github.com/hackiftekhar/IQKeyboardManager/compare/master...kmcgill88:829-Add-canBecomeActive?expand=1) that is working great for my needs. Instead of a `canBecomeActive` I went ahead and just destroyed the singleton altogether. 

In my case I'm using [KMKeys](https://github.com/kmcgill88/KMKeys-iOS),a library of mine which subscribes to the same events. The text field is not part of a view controller there so, `disabledDistanceHandlingClasses` won't work for me.

A quick solution is to just destroy it when I'm done and re-create before use.
```
    override func viewWillAppear(_ animated: Bool) {
        IQKeyboardManager.sharedManager().enable = true
        IQKeyboardManager.sharedManager().enableDebugging = true
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        IQKeyboardManager.destroy()
    }
```

Another idea would be simply hiding if visible then removing the observer. `NotificationCenter.default.removeObserver(self)` then adding the observers later again when needed.


Either way I think something like this could be introduced without affecting the current API.

**Comment by pilot34** [comment]
> I forked and made a couple of changes that is working great for my needs. 

good solution 👍

> @pilot34 I'm in the same position as you. Have you found a work around?

I removed IQKeyboardManager and implemented all keyboard staff manually... In my case it was easier then forking the lib.

**Comment by hackiftekhar** [comment]
First thing is that there is a separate property to enable/disable keyboard toolbar. The second thing is that there was a workaround for handling the issue with textFieldDidBeginEditing, with master branch now I've fixed this issue. Third one is that I now added unregisterAllNotifications method to completely unregister for all notification at developer risk.

**Comment by pilot34** [comment]
> Third one is that I now added unregisterAllNotifications method to completely unregister for all notification at developer risk.

👍

**Comment by hackiftekhar** [comment]
That's the best line for developers I think @pilot34. ha ha ha.

**Comment by shahdhiren** [comment]
Is destroy method removed? I want to enable keyboard manager only in 2 of the screen. Is that possible?

`IQKeyboardManager.destroy()`
