### ISSUE TITLE
I can't use toolbar's next button although textView is exist at below..

### ISSUE THREAD

**Issue by seubseub** [hackiftekhar/IQKeyboardManager#837]
Hi I use your Nice and awesome library. Thank you :)

But I can't go next although textView is exist at below...

At first I thought that below option may affect toolbar's go next button,

```
while(IQKeyboardManager.sharedManager().canGoNext) {
            IQKeyboardManager.sharedManager().goNext()
        }
``` 

but when I remove above code and then build again, same result happen

![kakaotalk_photo_2017-04-26-19-03-40_59](https://cloud.githubusercontent.com/assets/16539714/25429442/f97abbd6-2ab3-11e7-942f-b2180c9d9d96.jpeg)

Did I do wrong thing? or Could you help me to solve this problem?

Thank you for reading my issue:)

**Comment by hackiftekhar** [comment]
Not sure what might be the issue, but I know that there are issues with the UITableView, UICollectionView because of complex hierarchy.

**Comment by seubseub** [comment]
@hackiftekhar Thank you for your reply. I'll try again. :)

**Comment by hackiftekhar** [comment]
@seubseub Technically the library cannot handle all the possible user scenarios due to a number of UI related configurations and user requirements. So if developer need to do some special or complex thing with keyboard or textfield then I suggest to disable library for that view controller and then write your own logic.

**Comment by seubseub** [comment]
@hackiftekhar ok... I'll consider about your comment. Maybe I should do or just disable it. Thank you for your replying.
