### ISSUE TITLE
View wont scroll back to default position

### ISSUE THREAD

**Issue by ArthurAlvarez** [hackiftekhar/IQKeyboardManager#848]
I have been using IQKeyboardManager for quite some time now and after updating the library from 4.0.6 to 4.0.9 (to avoid warnings on Xcode 8.3), a strange behavior started to happen.

I have a login screen where the library scrolls up the entire view when the user taps the login text field. But now when the text field editing ends and the view is supposed to scroll back to it's original place, it ends scrolling before the original place, leaving a black area on the footer of the screen.

I didn't change my implementation and it works fine on 4.0.6. What could it be?

**Comment by pardypanda** [comment]
Facing the same issue after updating from 4.0.6 to 4.0.8 to work on XCode 8.2 (Swift 3.0)

**Comment by ArthurAlvarez** [comment]
@pardypanda  Aparently removing the constraint mapping I had to IQLayoutGuideConstraint resolved the issue. Now I'm running v4.0.10 on Xcode 8.3 without the bug. I hope it works for you too!

**Comment by hackiftekhar** [comment]
btw, I didn't change anything related to scrolling behaviour with 4.0.10.

**Comment by pardypanda** [comment]
Nope v4.0.10 didn't solve my problem
I do not have any IQLayoutGuideConstraint set on the input text field. 
It was working fine with v4.0.6

Attaching screenshots 
1. Keyboard up: http://i.imgur.com/UD8E3bN.jpg
2. Keyboard dismissed: http://i.imgur.com/AOqKMUG.jpg

**Comment by pardypanda** [comment]
@hackiftekhar 
Hey, any idea on this?
Also, do you think it would be helpful to figure out the root cause if we can Skype or get on TeamViewer?

**Comment by hackiftekhar** [comment]
@pardypanda it looks very strange. btw I see that you are trying to implement something like chat page which might need some special configuration, I would suggest you to disable library on that screen and implement your own logic there.

If you still want to use IQKeyboardManager there then can you please provide demo project by reproducing the issue so that I can look into that?

**Comment by JenkinDU** [comment]
@pardypanda I remove the connection of IQLayoutGuideConstraint in the storyboard, it's worked. so if the following guide suitable for the ios11? @hackiftekhar
https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#working-with-toplayoutguide-and-bottomlayoutguide

**Comment by hackiftekhar** [comment]
@pardypanda No idea since I'm not able to reproduce this issue, if you could send me any demo so that I can take a look.

@JenkinDU I didn't do much testing of IQLayoutGuideConstraint with iOS11, so I can't say anything about it. However the problem goes away after removing IQLayoutGuideConstraint connection.
