### ISSUE TITLE
NOT working if "override func viewWillAppear(_ animated: Bool)" in UITableViewController

### ISSUE THREAD

**Issue by iSky2000** [hackiftekhar/IQKeyboardManager#850]
It works on other pages, but except the TableViewController when it has "override func viewWillAppear(_ animated: Bool)"

Xcode Version 8.3.2 (8E2002)
install through CocoaPods with pod 'IQKeyboardManagerSwift'

How can I fix this issue?

Thanks.

**Comment by hackiftekhar** [comment]
Library is disabled in UITableViewController because UITableViewController has it's own mechanism to move content above keyboard. But if you override viewWillAppear and didn't says super.viewWillAppear then UITableViewController disable it's default behaviour.

Make sure you are calling super viewWillAppear.
