### ISSUE TITLE
App Rejected: uses or references the non-public APIs

### ISSUE THREAD

**Issue by firozkhan09** [hackiftekhar/IQKeyboardManager#865]
My Application uses IQKeyboardManager, which was recently rejected by Apple app store for the below mentioned reason.

_**Guideline 2.5.1 - Performance - Software Requirements

Additionally, your app uses or references the following non-public APIs:

_UIAlertControllerTextField, _UIAlertControllerTextFieldViewController, _UIQueuingScrollView, UIAlertSheetTextField, UISearchBarTextField, UITableViewWrapperView, UIToolbarButton, UIToolbarTextButton

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.**_

Is there a way by which I could upload my application using IQKeyboardManager to app store?
Kindly guide me through any other steps that may help me for resolving this issue.

**Comment by hackiftekhar** [comment]
That's not a goo news @firozkhan09, can you please tell apple that we are using this library and using these references only for workarounds?

**Comment by xiaodian** [comment]
I have also met this question.

**Comment by xiaodian** [comment]
@hackiftekhar

**Comment by Singsmlie** [comment]
@hackiftekhar ,I have also met this question.

**Comment by yanyufzf00** [comment]
@hackiftekhar ,I have also met this question.

**Comment by hackiftekhar** [comment]
Can you guys let me know what should be the best solution to overcome this?

**Comment by Singsmlie** [comment]
@hackiftekhar let the class string base64， and decode  when  use， I will try， if pass the review， i will notice you

**Comment by kedu** [comment]
我也被拒了,用的最新版本的,是不是旧版本不会?

**Comment by hackiftekhar** [comment]
Just to let you all know, v4.0.10 has been pushed with some workarounds to cheat apple. Let me know what apple respond with this latest version.

**Comment by hackiftekhar** [comment]
Hey @firozkhan09, @xiaodian, @Singsmlie, @yanyufzf00 can you guy let me know if you got success approving your app in app store with v4.0.10 version?

**Comment by firozkhan09** [comment]
After long waiting of review process Apple again reject the app with given reason

> We noticed that your app contains hidden features. Specifically, this app's IQToolBar obfuscation of using hasSuffix: and hasPrefix: is not compliant and must be removed. It would be appropriate to remove this private API use instead of hiding it.

You will experience a delayed review process if you deliberately disregard the App Store Review Guidelines, ignore previous rejection feedback in future app submissions, or use your app to mislead or deceive users.

> 


Its not working, need to find some way to do so without using non-public API's

**Comment by hackiftekhar** [comment]
@firozkhan09 hmm, ok, then I can technically explain why I'm referencing those private API's and we can find a solution.

So as you all know the IQToolbar can have title in the middle. So what I'm doing there is that I'm finding left barbutton frame and right barbutton frame, so that I can calculate the distance between left-right button.

Left Bar Button <----------- Distance X -------------> Right Bar Button

There are some more other views in the toolbar subview that's why I have to check if the bar button is kind of UIToolbarButton or UIToolbarTextButton, in this way I can be sure that it's the button I'm trying to find.

That's why I'm using those class names in IQToolbar. However I'm not using those private class to mislead something or try to alter something.

I think all of us can should try different solutions and let's see what apple approves. Then we can update the library with that solution.

**Comment by beuady** [comment]
Hello,hackiftekhar.
I have also met this question. And then show you my reject reason: 
//===============
Your app uses or references the following non-public APIs:

LSApplicationWorkspace, defaultWorkspace, openSensitiveURL:withOptions:, UIInputSetHostView, _UIAlertControllerTextFieldViewController, _UIAlertControllerTextField

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.
//================
Hoping help for solve this question. Thank you.

**Comment by hackiftekhar** [comment]
Hey @beaudy, we already removed _UIAlertControllerTextFieldViewController, _UIAlertControllerTextField private API usage in latest release. Other private API's you mentioned is not due to my library.

**Comment by ArthurAlvarez** [comment]
@hackiftekhar what's the status on 4.0.10? Still rejected?

**Comment by kedu** [comment]
我回退到3.0.2成功,不过我是手动下载的.而且成功通过审核.

**Comment by hackiftekhar** [comment]
@ArthurAlvarez I don't know the actual status since I got success with approving a build, but @firozkhan09 build get rejected. @firozkhan09 Could you please let me know if you tried something else and approved the build?

**Comment by hackiftekhar** [comment]
@ArthurAlvarez @firozkhan09 I've also converted some of other private API calls using public API with this commit 96b0f077a78efdc68e30fbb53af0e993db97be24 it would be better if you try with the master branch code now.

**Comment by iamgod588** [comment]
I have also met this question,and i don't know you add the bug label to this question,can you tell me the reason please

**Comment by feng520ckx** [comment]
@hackiftekhar 
I used the string with base64 encryption, successfully passed the review

```

#define kUIBase64 [@"_UI" sq_base64EncodedString]

 NSString *classNameString = [NSStringFromClass([superview class])sq_base64EncodedString];
if ([superview.superview isKindOfClass:[UITableView class]] == NO 
&&[superview.superview isKindOfClass:[UITableViewCell class]] == NO 
&&[classNameString hasPrefix:kUIBase64] == NO)
 {
           return superview;
}
```

**Comment by hackiftekhar** [comment]
That's super great @feng520ckx, however there is another good news. I've removed all the private API references. I believe the app will not be rejected anymore.
