### ISSUE TITLE
textFieldShouldBeginEditing called multiple times 

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#88]
This method is calling multiple times if I disable Toolbar, it will not call multiple times, but I want your toolbar.
```
-(BOOL)textFieldShouldBeginEditing:(UITextField *)textField{

return YES;

}
```

in my App, i have a Country text field where I don't want the user to type so when user tap on that text field it should open my popup or modal .. so any workaround?

**Comment by seriyvolk83** [comment]
It must not all textFieldShouldBeginEditing on each field. It must call it only for the tapped text field.

**Comment by seriyvolk83** [comment]
How to turn off this useless feature? It's definitely wrong. What is the reason of calling it on each field? I want to show dropdown list instead of editing the field, but focusing on ANY text field my dropdown is opened because you call textFieldShouldBeginEditing on EACH field.

**Comment by hackiftekhar** [comment]
@seriyvolk83 looks like you didn't neither read Manual Management Guide or read the comments of this issue. `textFieldShouldBeginEditing` doesn't directly called by my library. The library is calling native `canBecomeFirstResponder` method to know if a textField can become first responder or not, and the iOS call `textFieldShouldBeginEditing` internally. So library is not directly responsible to calling this method but the iOS SDK. That's why I've added some workaround to overcome with this situation.

**Comment by hackiftekhar** [comment]
@seriyvolk83 If you have any better approach then please share with us.

**Comment by seriyvolk83** [comment]
@hackiftekhar Right, I already found this documentation. But as a new user it's very unpredictable that it works so by default. May be you need to turn off this by default and a developer will manually turn on if he needs this. Currently you change the expected behavior iOS. What for example if this lib is added to an existing app just for one work. If textFieldShouldBeginEditing is used in another places this library will introduce bugs that are not clear and will be found only when users will start to use it.

**Comment by seriyvolk83** [comment]
@hackiftekhar textFieldShouldBeginEditing means "textField Should Begin Editing". If I tap on a particular field, then why you ask other fields? They never should begin being edited in this case.
I think if the default behavior of this method is to return YES, and if it is invoked twice on the tapped field then why not to add another custom method instead of canBecomeFirstResponder that can be invoked on each field and textFieldShouldBeginEditing will be invoked only once at the end (as it works in iOS). Developers can use that new method to do what they want instead of working around.

**Comment by hackiftekhar** [comment]
100% Correct @seriyvolk83 
> textFieldShouldBeginEditing means "textField Should Begin Editing".

So this method expect to return YES or NO, so why you are writing your main work inside that method. You should only write logic to decide return YES or NO.

**Comment by seriyvolk83** [comment]
@hackiftekhar Because I don't want the keyboard to appear. If I will return just NO, then I will have no ability to show a dropdown list instead. So, I do it here. If I will move dropdown logic into another method, then I will have to return YES here and the keyboard will appear for a moment.

**Comment by seriyvolk83** [comment]
@hackiftekhar What is the reason of having text field that exists and just return NO in  textFieldShouldBeginEditing? We would never can edit it. Why to have the field, then? For disabling the field we have a special flag, so..

**Comment by hackiftekhar** [comment]
I know my bro @seriyvolk83 this is why I suggested some workarounds.

Library uses `canBecomeFirstResponder` method for calculating toolbar previous/next buttons state accurately. Most of the people need next/previous to work properly that's why this enabled by default. If you would like to totally get rid of this nonsense then you can simply set `enableAutoToolbar` to NO. So you'll not get multiple callbacks in that delegate method.

**Comment by seriyvolk83** [comment]
@hackiftekhar Looks like you right. And this is a bug of iOS because in documentation there is the following:
```
Before becoming the first responder, the text field calls its delegate’s textFieldShouldBeginEditing(_:) method. Use that method to allow or prevent the editing of the text field’s contents.
```

So, textFieldShouldBeginEditing definitely should not be called from canBecomeFirstResponder.

May be the better place for my dropdown is becomeFirstResponder() method.

Or I can override canBecomeFirstResponder and return YES without calling super or delegate.

**Comment by seriyvolk83** [comment]
Or you can right a hack and remove delegate before calling canBecomeFirstResponder.

**Comment by hackiftekhar** [comment]
@seriyvolk83 Cannot do that because when textField is enabled then only delegate method know if a textField can become first responder or not. That's why system use delegate method, otherwise if I write your suggested hack then canBecomeFirstResponder will always return YES if textfield is enabled.

**Comment by anishparajuli555** [comment]
I too faced this problem..A way to solve this is 

  ```
  func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        
        if  textField == genderTxtField && textField.isFirstResponder {
            
            genderTxtField.resignFirstResponder()
            //do your work
            return false
            
        }
        return true
    }
```

**Comment by yasirmturk** [comment]
`isFirstResponder` is alway false at `textFieldShouldBeginEditing`  until `textFieldDidBeginEditing` ...

**Comment by yasirmturk** [comment]
@hackiftekhar your workaround solution `UIControlEventTouchDown` wont work as touch events are not called on `UITextField` .. plz verify?

**Comment by hackiftekhar** [comment]
@yasirmturk Have you tried adding UIControlEventTouchDown event since when I checked this at that time it was working correctly.

**Comment by yasirmturk** [comment]
yes i did and it was not working so i used the 2nd solution unwillingly :)

**Comment by Shahbaz-Akram** [comment]
Same issue textFieldShouldBeginEditing calls multiple time face in version # 4.0.8. How to handled this?

**Comment by Shahbaz-Akram** [comment]
@anishparajuli555 Your method work but keyboard not hide when want to move on next screen after click on specfic textfield.

**Comment by hackiftekhar** [comment]
@all, Due to seeing too many issues reported for `textFieldShouldBeginEditing call multiple times`, I know that it's due to the Apple API's limitation. But I decided to remove validating `canBecomeFirstResponder` calls to fix this issue for `IQKeyboardManager` library, so this delegate method will not be called multiple times, but developers need to update their logic they wrote with `isAskingCanBecomeFirstResponder`. This variable will also be deprecated and will be removed in future releases.

This is my action plan:-
- Current CocoaPods version is 4.0.8. In next couple of days 4.0.9 will be pushed to CocoaPods with some bug fixes and improvements. 4.0.9 will be swift 3.1 compatible version.
- After 4.0.9, necessary changes will be made to remove `canBecomeFirstResponder` method call and `isAskingCanBecomeFirstResponder` will be put into the deprecated property list with warning text to inform developers about this. This code will be pushed to master.
- After successful testing of new changes regarding `canBecomeFirstResponder` we'll push 4.1.0 to CocoaPods (probably after 1 month of 4.0.9).
- In upcoming releases `isAskingCanBecomeFirstResponder` will be removed from library since this property was come to existence as a workaround to handle `textFieldShouldBeginEditing` issue, but after removing `canBecomeFirstResponder` method call, this property will make no sense.

Let me know if anyone has any thoughts or suggestion on this. I would love to hear.

**Comment by yasirmturk** [comment]
good decision.. keep it up

**Comment by kumardiwa** [comment]
is **isAskingCanBecomeFirstResponder**  is available in 4.0.10 ?

**Comment by hackiftekhar** [comment]
@kumardiwa the property is there in 4.0.10, but this property no longer has any effect since I did some other code changes to remove the need of this property. For now this property will always return NO.

This will completely be remove in v4.0.11

**Comment by kumardiwa** [comment]
@hackiftekhar My case is, I've 3 textfields in a viewcontroller but I want 1 of them should not be editable and I want some action when this textfield should begin editing so How can I do this. Even though I've desable IQKeyboard ( **IQKeyboardManager.sharedManager().enableAutoToolbar = false**)  in this View controller in viewWillApear method but still got the problem.

**Comment by hackiftekhar** [comment]
@kumardiwa So from now what will happen, when you tap on the enabled textfield then the delegate method will only be get called for that text field only and not for other textfields, so you can safely write your logic inside textFieldShouldBeginEditing and return NO for the textfield which you don't want to editable.

**Comment by kuyazee** [comment]
For some reason @anishparajuli555's workaround also works for me even though as explained by @yasirmturk 

> isFirstResponder is alway false at textFieldShouldBeginEditing until textFieldDidBeginEditing
