### ISSUE TITLE
UITextField autoscroll to just above keyboard, even if textfield is fully visible

### ISSUE THREAD

**Issue by sw-tt-harishmistry** [hackiftekhar/IQKeyboardManager#925]
I have a scrollview full of textfields almost 20 textfields. Now i follow below steps to reproduce this issue:

1.) Scroll down to 20th textfield and tap on it it will open keyboard
2.) Now 12th textfield is at top and is visible, now if i tap on 12th textfield it automatically scrolls down to position just above keyboard which leads to a bad user experience.

If a textfield is already in visible area why it needs to be repositioned or scrolled.

I have also attached snapshots for your reference.

![1](https://user-images.githubusercontent.com/22932055/29114753-e44e8880-7d12-11e7-8fda-c3f843617ef6.png)
![2](https://user-images.githubusercontent.com/22932055/29114755-e4a06ff6-7d12-11e7-92f9-88b095a4cbe3.png)

**Comment by TheMrugraj** [comment]
I agree with the author of issue @sw-tt-harishmistry 
I also faced this issue in past. In stead of giving smooth and easy transition sometimes it jerks down and moves to the selected Input field.

**Comment by harish-mistry** [comment]
I also agree with the author of issue @sw-tt-harishmistry.

I have also faced this issue in past. In stead of giving smooth and easy transition sometimes it jerks down and moves to the selected Input field. Ultimately leads to a bad user experience.

**Comment by kushanshah11** [comment]
I also agree with the author of issue @sw-tt-harishmistry.

I have also faced this issue in past. In stead of giving smooth and easy transition sometimes it jerks down and moves to the selected Input field. Ultimately leads to a bad user experience.

**Comment by PatelArpit** [comment]
I also agree with the author of issue @sw-tt-harishmistry.

I have also faced this issue in past. In stead of giving smooth and easy transition sometimes it jerks down and moves to the selected Input field. Ultimately leads to a bad user experience.

**Comment by vanditmehta** [comment]
getting same issue.

Do we have any way to handle this issue?

**Comment by sw-tt-abhayrajvala** [comment]
I also agree with the author of issue @sw-tt-harishmistry.
If a textfield is already in visible area why it needs to be repositioned or scrolled.

**Comment by sw-tt-vipulparmar** [comment]
I also agree with the author of issue @sw-tt-harishmistry.
is there any way to handle this issue?
Thanks in advance

**Comment by sw-tt-milanpatel** [comment]
I also agree with the author of issue @sw-tt-harishmistry.
Is there any way to handle this issue?

**Comment by sw-tt-jethanandnandpal** [comment]
I agree with @sw-tt-harishmistry. Is there any way to handle this issue?

**Comment by sw-tt-sandipprajapati** [comment]
Hi @hackiftekhar, I have agree with this issue.

**Comment by hackiftekhar** [comment]
@sw-tt-harishmistry It's because of reusable cell concept of UITableView, give me 30 minutes I'm writing a detailed explanation and then we can agree on a solution.

**Comment by sw-tt-harishmistry** [comment]
@hackiftekhar, i have not used any UITableView here, as i have mentioned its simple UIScrollView and the text-feilds in it. So i think you are misunderstanding my question. Let me know if you need more details on the same.

Thank you.

**Comment by hackiftekhar** [comment]
I know you are using UIScrollView, but currently there is no explicit validation for UITableView that's why library is running same code for UIScrollView and all it's subclasses.

**Comment by sw-tt-harishmistry** [comment]
Okay, so is there any fix to this issue, It will be really very helpfull.

**Comment by sw-tt-rushabhpatel** [comment]
@sw-tt-harishmistry I have faced similar  issue in my previous project .Thanks for asking question here. Hope someone will resolved this issue  in next release.

**Comment by hackiftekhar** [comment]
Attaching some screenshots for better understanding why library pull current textField to keyboard.

![simulator screen shot 09-aug-2017 3 54 48 pm](https://user-images.githubusercontent.com/3831495/29118128-5fa3e3e4-7d1e-11e7-810f-cdc3cc6b9ad2.png)
![simulator screen shot 09-aug-2017 3 53 54 pm](https://user-images.githubusercontent.com/3831495/29118127-5fa392fe-7d1e-11e7-833e-54955bc143b4.png)
![simulator screen shot 09-aug-2017 3 54 01 pm](https://user-images.githubusercontent.com/3831495/29118126-5fa34ec0-7d1e-11e7-96d0-cf3fd38b8e82.png)

### According to me here are 2 suggestions we can try to do:-

**1)** Add explicit validations of UITableView/UICollectionView so that we'll only pull textField if it's within UITableView/UICollectionView, otherwise keep textField position as it is.
**Pros:-** UIScrollView will start behaving as expected. UITableView/UICollectionView will still display almost correct state of previous button.
**Cons:-** UITableView/UICollectionView will still have old behaviour and will still pull textField's which might look weird.

**2)** Remove pulling textField code so that library will not pull any textField either it's inside UIScrollView or it's subclasses view's.
**Pros:-** UIScrollView/UITableView/UICollectionView will all looks great and will not pull textField.
**Cons:-** If keyboard is shown in textField contains within UITableView/UICollectionView then there might be chance that previous button will be disabled in the top most cell.

**If you have some suggestions other than above 2 then I'm eager to hear from you guys. But before providing any suggestion, I would like you to take a look at `Special case for ScrollView` around line 735 to 857 which is within `adjustFrame` method of `IQKeyboardManager`.**

**Comment by sw-tt-harishmistry** [comment]
@hackiftekhar, As per you explanation its because of reusability of cells, but i told you earlier all textfields are having their own ownership in memory because i am not using UITableView thus there is no UITableViewCell here, i have placed individual textfields in UIScrollview. Why you are assuming this as reusable cell i am not understanding.

Please find attachment of my source code in which i am facing this issue and it is not having any UITableView or UITableViewCell here.

[Keyboards.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1211205/Keyboards.zip)

**Comment by sw-tt-harishmistry** [comment]
@hackiftekhar, Why are you pointing to Previous and Next arrow buttons, my question here is not about the buttons but about the autoscroll behavior of UITextFields even they are in visible areas.

**Comment by hackiftekhar** [comment]
@sw-tt-harishmistry I'm properly understanding that you are using UIScrollView and there are no reusable cells and it should work fine for your scenario, but my brother please try to read my message again I already answered you this in my previous messages:-

`I know you are using UIScrollView, but currently there is no explicit validation for UITableView that's why library is running same code for UIScrollView and all it's subclasses.`

That's why it's behaving same for UIScrollView.

**Comment by sw-tt-harishmistry** [comment]
@hackiftekhar, can you just check the source code i have shared and, provide solution of this issue ?
It will be really helpful.

**Comment by hackiftekhar** [comment]
Regarding the autoscroll and previous button pointing, there is indirect relationship I explained in my message you might have not read properly. So I would suggest you to understand the connection between autoscrolling and previous buttons.

**Comment by hackiftekhar** [comment]
There is no solution for now @sw-tt-harishmistry, that's why I suggested 2 approaches. Looks like you might also haven't read the source code I suggested in same message.

**Comment by sw-tt-harishmistry** [comment]
@hackiftekhar, thanks for your feedbacks

**Comment by daurenm** [comment]
Is it possible to just disable previous button, so no scrolling takes place when textfield at the top?

**Comment by hackiftekhar** [comment]
1. Nope.
2. I have to do code changes.

**Comment by RakeshKumarVerma** [comment]
Hi... i am agree with this issue and more frasted, after lots of rnd i found some solution. First please click on our scrollview, and  select attribute inspector and uncheck the "Content Touch" and after check your scrollview. my problem is solve by this trick,  i hope your problem is solve.
