### ISSUE TITLE
ToolBar issues

### ISSUE THREAD

**Issue by winterWD** [hackiftekhar/IQKeyboardManager#956]
Done button is visible but another up and down buttons are not visible. I am using Xcode 8.3.3, swift and carthage. IQKeyboardManager at "v4.0.13"
![wx20170906-144255](https://user-images.githubusercontent.com/14071671/30111779-98303d32-9341-11e7-9a8e-ee28313f4247.png)

**Comment by hackiftekhar** [comment]
Your both textfields aren't on the same view that's why next/prev button doesn't display. You have two solutions
1) Keep both textField on the same view.
2) Use IQPreviousNextView as the container view of both of your textView content view. See the demo project how you should place IQPreviousNextView.

**Comment by winterWD** [comment]
ah, thank you very much, I got it.
