### ISSUE TITLE
Next previous not working properly sometimes for textfields in UItableview

### ISSUE THREAD

**Issue by PrasadPotale** [hackiftekhar/IQKeyboardManager#96]
Hello Mohd, 

First of all thank you very much for creating such a useful keyboard manager.

We have started using it in our each and every project, in one of the project where we are showing Collapsing table view sections, we are facing one issue as sometimes tableview cells are not dequeued and its trying to go to that textfield on click of previous or next button, then keyboards previous, next, return buttons are not working.

We have created a sample for that, it will be great help for us if you can guide us to fix that issue.

you can download sample code from following link.

https://www.dropbox.com/s/qfsqmwfh6nyfu1m/PKCollapsingTableViewSections-master.zip?dl=0

Thanks.

**Comment by hackiftekhar** [comment]
Optimized next/previous logic for UITableView/UICollectionView. But still sometimes when top/bottom cell doesn't exist in UITableView due to dequeue logic, then next/previous logic fails and we know it can't be fixed.

**Comment by mihirpmehta** [comment]
Hey hackiftekhar, 

Thanks for the wonderful library first of all, I am still facing this issue with done button. when pressing done button the cursor goes to first row's textfield instead of last. 

I know it's happening because dequeuing of cells. I am just wondering if there is any workaround around this things. 

Thanks

**Comment by Shamsiddin** [comment]
> But still sometimes when top/bottom cell doesn't exist in UITableView due to dequeue logic, then next/previous logic fails and we know it can't be fixed.

Hi hackiftekhar, I have some solution for this issue, maybe it helps.
Do to invisible cells are not on the view hierarchy, `textField` can't be first responder, for this reason don't move focus onto `textField` unless it's visible, but first of all move your `cell` (with `textField`) to the visible area and then make it first responder. Hope it helps.

**Comment by hackiftekhar** [comment]
@Shamsiddin it's a good solution at first look, but still we don't know if the invisible cell has textFields or not. That's why library cannot identify if it needs to enable previous button or disable it. Do you have any idea about it?

**Comment by Shamsiddin** [comment]
I'll dive a little into your library and give you note as far as I can. But you can without any problem catch `textField` from invisible cells if they have.

**Comment by hackiftekhar** [comment]
It will work if user uses unique cell identifier for each cell, but will not work if user has same cell identifier, because a cell may be reused at any other indexPath. For example if cell was using at 3rd row previously then on reusing the cell may use at 10th position and any other, so it's harder than we think. Do you have any other proposed solution?
